/*
 * Copyright (c)  2005-2008, Stanford University
 * Use of the OpenSim software in source form is permitted provided that the following
 * conditions are met:
 * 	1. The software is used only for non-commercial research and education. It may not
 *     be used in relation to any commercial activity.
 * 	2. The software is not distributed or redistributed.  Software distribution is allowed 
 *     only through https://simtk.org/home/opensim.
 * 	3. Use of the OpenSim software or derivatives must be acknowledged in all publications,
 *      presentations, or documents describing work in which OpenSim or derivatives are used.
 * 	4. Credits to developers may not be removed from executables
 *     created from modifications of the source.
 * 	5. Modifications of source code must retain the above copyright notice, this list of
 *     conditions and the following disclaimer. 
 * 
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 *  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 *  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
 *  SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 *  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; 
 *  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 *  OR BUSINESS INTERRUPTION) OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY
 *  WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/*
 * ModelSelectionJPanel.java
 *
 * Created on May 21, 2007, 2:55 PM
 */

package org.opensim.view;

import java.util.Observable;
import java.util.Observer;
import java.util.Vector;
import javax.swing.JComboBox;
import org.opensim.modeling.Model;
import org.opensim.modeling.OpenSimObject;
import org.opensim.view.pub.OpenSimDB;

/**
 *
 * @author  Ayman
 */
public class ModelSelectionJPanel extends javax.swing.JPanel implements Observer{
   
   private static String noModelString="No Models";
   /** Creates new form ModelSelectionJPanel */
   public ModelSelectionJPanel() {
      initComponents();
      OpenSimDB.getInstance().addObserver(this);
      update();
   }
   
   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabelForCurrentModelComboBox = new javax.swing.JLabel();
        jCurrentModelComboBox = new javax.swing.JComboBox();

        setMaximumSize(new java.awt.Dimension(151, 42));
        setMinimumSize(new java.awt.Dimension(151, 42));
        jLabelForCurrentModelComboBox.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelForCurrentModelComboBox.setLabelFor(jCurrentModelComboBox);
        jLabelForCurrentModelComboBox.setText("Model");
        jLabelForCurrentModelComboBox.setMaximumSize(new java.awt.Dimension(37, 42));
        jLabelForCurrentModelComboBox.setMinimumSize(new java.awt.Dimension(37, 42));
        jLabelForCurrentModelComboBox.setPreferredSize(new java.awt.Dimension(37, 42));

        jCurrentModelComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Models" }));
        jCurrentModelComboBox.setToolTipText("Current model");
        jCurrentModelComboBox.setMaximumSize(new java.awt.Dimension(200, 20));
        jCurrentModelComboBox.setMinimumSize(new java.awt.Dimension(200, 20));
        jCurrentModelComboBox.setPreferredSize(new java.awt.Dimension(200, 20));
        jCurrentModelComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCurrentModelSelectActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabelForCurrentModelComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jCurrentModelComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(jLabelForCurrentModelComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jCurrentModelComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

   private void jCurrentModelSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCurrentModelSelectActionPerformed
      Object selected = ((JComboBox)evt.getSource()).getSelectedItem();
      if (selected instanceof String || selected ==null)  // No model
         return;
      Model selectedModel = (Model) selected;
      if (OpenSimDB.getInstance().getCurrentModel()!=selectedModel){
         OpenSimDB.getInstance().deleteObserver(this);
         OpenSimDB.getInstance().setCurrentModel(selectedModel);
         OpenSimDB.getInstance().addObserver(this);
      }
// TODO add your handling code here:
   }//GEN-LAST:event_jCurrentModelSelectActionPerformed
   // This should be invoked only if the user changes model from dropdown   // The events we care about are a model becoming current or a model getting deleted so that there's no more
   // current model'
   public void update(Observable o, Object arg) {
      if (o instanceof OpenSimDB){
         // if current model is being switched due to open/close or change current then
         // update list of coordinates
         if (arg instanceof ModelEvent) {
            final ModelEvent evt = (ModelEvent)arg;
            if (evt.getOperation()==ModelEvent.Operation.SetCurrent){
               update(); // update the list 
               // The reason we get the Model is because otherwise 
               // setSelectedItem triggers another round of DB updates!
               jCurrentModelComboBox.getModel().setSelectedItem(evt.getModel());
            }
            else if (evt.getOperation()==ModelEvent.Operation.Close){
               update();
            }
         } else if (arg instanceof ObjectSetCurrentEvent) {
            // If the current model is being switched due to a change current event,
            // then update the list of models.
            ObjectSetCurrentEvent evt = (ObjectSetCurrentEvent)arg;
            Vector<OpenSimObject> objs = evt.getObjects();
            for (int i=0; i<objs.size(); i++) {
               if (objs.get(i) instanceof Model) {
                  Model currentModel = (Model)objs.get(i);
                  update(); // update the list 
                  // The reason we get the Model is because otherwise 
                  // setSelectedItem triggers another round of DB updates!
                  jCurrentModelComboBox.getModel().setSelectedItem(currentModel);
                  break;
               }
            }
         } else if (arg instanceof ObjectsAddedEvent) {
            //update();
         }
      }
  }

   private void update() {
      Object[] models = OpenSimDB.getInstance().getAllModels();
      jCurrentModelComboBox.setEnabled(models.length!=0);
      if (models.length==0){
         jCurrentModelComboBox.removeAllItems();
         jCurrentModelComboBox.addItem(noModelString);
         // disable components
         jLabelForCurrentModelComboBox.setEnabled(false);
         jCurrentModelComboBox.setEnabled(false);
      }
      else {
         // Populate
         jCurrentModelComboBox.removeAllItems();
         for(int i=0; i<models.length; i++){
            jCurrentModelComboBox.addItem((Model)models[i]);
         }
         // enable components
         jLabelForCurrentModelComboBox.setEnabled(true);
         jCurrentModelComboBox.setEnabled(true);
      }
   }
   
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jCurrentModelComboBox;
    private javax.swing.JLabel jLabelForCurrentModelComboBox;
    // End of variables declaration//GEN-END:variables

}
