/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class ComponentIsAnOrphan extends OpenSimException {
  private transient long swigCPtr;

  public ComponentIsAnOrphan(long cPtr, boolean cMemoryOwn) {
    super(opensimCommonJNI.ComponentIsAnOrphan_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ComponentIsAnOrphan obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimCommonJNI.delete_ComponentIsAnOrphan(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ComponentIsAnOrphan(String file, long line, String func, String thisName, String componentConcreteClassName) {
    this(opensimCommonJNI.new_ComponentIsAnOrphan(file, line, func, thisName, componentConcreteClassName), true);
  }

}
