/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class EmptyFileName extends InvalidArgument {
  private long swigCPtr;

  public EmptyFileName(long cPtr, boolean cMemoryOwn) {
    super(opensimModelCommonJNI.EmptyFileName_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(EmptyFileName obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimModelCommonJNI.delete_EmptyFileName(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public EmptyFileName(String file, long line, String func) {
    this(opensimModelCommonJNI.new_EmptyFileName(file, line, func), true);
  }

}
