/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class MatrixBaseVec6 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public MatrixBaseVec6(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(MatrixBaseVec6 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimSimbodyJNI.delete_MatrixBaseVec6(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int nrow() {
    return opensimSimbodyJNI.MatrixBaseVec6_nrow(swigCPtr, this);
  }

  public int ncol() {
    return opensimSimbodyJNI.MatrixBaseVec6_ncol(swigCPtr, this);
  }

  public boolean isResizeable() {
    return opensimSimbodyJNI.MatrixBaseVec6_isResizeable(swigCPtr, this);
  }

  public MatrixBaseVec6() {
    this(opensimSimbodyJNI.new_MatrixBaseVec6__SWIG_0(), true);
  }

  public MatrixBaseVec6(int m, int n) {
    this(opensimSimbodyJNI.new_MatrixBaseVec6__SWIG_1(m, n), true);
  }

  public void clear() {
    opensimSimbodyJNI.MatrixBaseVec6_clear(swigCPtr, this);
  }

  public MatrixBaseVec6 setTo(Vec6 t) {
    return new MatrixBaseVec6(opensimSimbodyJNI.MatrixBaseVec6_setTo(swigCPtr, this, Vec6.getCPtr(t), t), false);
  }

  public MatrixBaseVec6 setToNaN() {
    return new MatrixBaseVec6(opensimSimbodyJNI.MatrixBaseVec6_setToNaN(swigCPtr, this), false);
  }

  public MatrixBaseVec6 setToZero() {
    return new MatrixBaseVec6(opensimSimbodyJNI.MatrixBaseVec6_setToZero(swigCPtr, this), false);
  }

  public RowVectorViewVec6 row(int i) {
    return new RowVectorViewVec6(opensimSimbodyJNI.MatrixBaseVec6_row(swigCPtr, this, i), true);
  }

  public RowVectorViewVec6 updRow(int i) {
    return new RowVectorViewVec6(opensimSimbodyJNI.MatrixBaseVec6_updRow(swigCPtr, this, i), true);
  }

  public VectorViewVec6 col(int j) {
    return new VectorViewVec6(opensimSimbodyJNI.MatrixBaseVec6_col(swigCPtr, this, j), true);
  }

  public VectorViewVec6 updCol(int j) {
    return new VectorViewVec6(opensimSimbodyJNI.MatrixBaseVec6_updCol(swigCPtr, this, j), true);
  }

  public Vec6 getElt(int i, int j) {
    return new Vec6(opensimSimbodyJNI.MatrixBaseVec6_getElt(swigCPtr, this, i, j), false);
  }

  public Vec6 updElt(int i, int j) {
    return new Vec6(opensimSimbodyJNI.MatrixBaseVec6_updElt(swigCPtr, this, i, j), false);
  }

  public MatrixBaseVec6 negateInPlace() {
    return new MatrixBaseVec6(opensimSimbodyJNI.MatrixBaseVec6_negateInPlace(swigCPtr, this), false);
  }

  public MatrixBaseVec6 resize(int m, int n) {
    return new MatrixBaseVec6(opensimSimbodyJNI.MatrixBaseVec6_resize(swigCPtr, this, m, n), false);
  }

  public MatrixBaseVec6 resizeKeep(int m, int n) {
    return new MatrixBaseVec6(opensimSimbodyJNI.MatrixBaseVec6_resizeKeep(swigCPtr, this, m, n), false);
  }

  public void lockShape() {
    opensimSimbodyJNI.MatrixBaseVec6_lockShape(swigCPtr, this);
  }

  public void unlockShape() {
    opensimSimbodyJNI.MatrixBaseVec6_unlockShape(swigCPtr, this);
  }

  public final static int NScalarsPerElement = opensimSimbodyJNI.MatrixBaseVec6_NScalarsPerElement_get();
  public final static int CppNScalarsPerElement = opensimSimbodyJNI.MatrixBaseVec6_CppNScalarsPerElement_get();

}
