/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class Millard2012AccelerationMuscle extends Muscle {
  private long swigCPtr;

  public Millard2012AccelerationMuscle(long cPtr, boolean cMemoryOwn) {
    super(opensimModelJNI.Millard2012AccelerationMuscle_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Millard2012AccelerationMuscle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimModelJNI.delete_Millard2012AccelerationMuscle(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static Millard2012AccelerationMuscle safeDownCast(OpenSimObject obj) {
    long cPtr = opensimModelJNI.Millard2012AccelerationMuscle_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new Millard2012AccelerationMuscle(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimModelJNI.Millard2012AccelerationMuscle_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimModelJNI.Millard2012AccelerationMuscle_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimModelJNI.Millard2012AccelerationMuscle_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new Millard2012AccelerationMuscle(cPtr, false);
  }

  public String getConcreteClassName() {
    return opensimModelJNI.Millard2012AccelerationMuscle_getConcreteClassName(swigCPtr, this);
  }

  public void setPropertyIndex_default_activation(SWIGTYPE_p_PropertyIndex value) {
    opensimModelJNI.Millard2012AccelerationMuscle_PropertyIndex_default_activation_set(swigCPtr, this, SWIGTYPE_p_PropertyIndex.getCPtr(value));
  }

  public SWIGTYPE_p_PropertyIndex getPropertyIndex_default_activation() {
    return new SWIGTYPE_p_PropertyIndex(opensimModelJNI.Millard2012AccelerationMuscle_PropertyIndex_default_activation_get(swigCPtr, this), true);
  }

  public void copyProperty_default_activation(Millard2012AccelerationMuscle source) {
    opensimModelJNI.Millard2012AccelerationMuscle_copyProperty_default_activation(swigCPtr, this, Millard2012AccelerationMuscle.getCPtr(source), source);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_double_t getProperty_default_activation() {
    return new SWIGTYPE_p_OpenSim__PropertyT_double_t(opensimModelJNI.Millard2012AccelerationMuscle_getProperty_default_activation(swigCPtr, this), false);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_double_t updProperty_default_activation() {
    return new SWIGTYPE_p_OpenSim__PropertyT_double_t(opensimModelJNI.Millard2012AccelerationMuscle_updProperty_default_activation(swigCPtr, this), false);
  }

  public double get_default_activation(int i) {
    return opensimModelJNI.Millard2012AccelerationMuscle_get_default_activation__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_default_activation(int i) {
    return new SWIGTYPE_p_double(opensimModelJNI.Millard2012AccelerationMuscle_upd_default_activation__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_default_activation(int i, double value) {
    opensimModelJNI.Millard2012AccelerationMuscle_set_default_activation__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_default_activation(double value) {
    return opensimModelJNI.Millard2012AccelerationMuscle_append_default_activation(swigCPtr, this, value);
  }

  public void constructProperty_default_activation(double initValue) {
    opensimModelJNI.Millard2012AccelerationMuscle_constructProperty_default_activation(swigCPtr, this, initValue);
  }

  public double get_default_activation() {
    return opensimModelJNI.Millard2012AccelerationMuscle_get_default_activation__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_default_activation() {
    return new SWIGTYPE_p_double(opensimModelJNI.Millard2012AccelerationMuscle_upd_default_activation__SWIG_1(swigCPtr, this), false);
  }

  public void set_default_activation(double value) {
    opensimModelJNI.Millard2012AccelerationMuscle_set_default_activation__SWIG_1(swigCPtr, this, value);
  }

  public void setPropertyIndex_default_fiber_length(SWIGTYPE_p_PropertyIndex value) {
    opensimModelJNI.Millard2012AccelerationMuscle_PropertyIndex_default_fiber_length_set(swigCPtr, this, SWIGTYPE_p_PropertyIndex.getCPtr(value));
  }

  public SWIGTYPE_p_PropertyIndex getPropertyIndex_default_fiber_length() {
    return new SWIGTYPE_p_PropertyIndex(opensimModelJNI.Millard2012AccelerationMuscle_PropertyIndex_default_fiber_length_get(swigCPtr, this), true);
  }

  public void copyProperty_default_fiber_length(Millard2012AccelerationMuscle source) {
    opensimModelJNI.Millard2012AccelerationMuscle_copyProperty_default_fiber_length(swigCPtr, this, Millard2012AccelerationMuscle.getCPtr(source), source);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_double_t getProperty_default_fiber_length() {
    return new SWIGTYPE_p_OpenSim__PropertyT_double_t(opensimModelJNI.Millard2012AccelerationMuscle_getProperty_default_fiber_length(swigCPtr, this), false);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_double_t updProperty_default_fiber_length() {
    return new SWIGTYPE_p_OpenSim__PropertyT_double_t(opensimModelJNI.Millard2012AccelerationMuscle_updProperty_default_fiber_length(swigCPtr, this), false);
  }

  public double get_default_fiber_length(int i) {
    return opensimModelJNI.Millard2012AccelerationMuscle_get_default_fiber_length__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_default_fiber_length(int i) {
    return new SWIGTYPE_p_double(opensimModelJNI.Millard2012AccelerationMuscle_upd_default_fiber_length__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_default_fiber_length(int i, double value) {
    opensimModelJNI.Millard2012AccelerationMuscle_set_default_fiber_length__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_default_fiber_length(double value) {
    return opensimModelJNI.Millard2012AccelerationMuscle_append_default_fiber_length(swigCPtr, this, value);
  }

  public void constructProperty_default_fiber_length(double initValue) {
    opensimModelJNI.Millard2012AccelerationMuscle_constructProperty_default_fiber_length(swigCPtr, this, initValue);
  }

  public double get_default_fiber_length() {
    return opensimModelJNI.Millard2012AccelerationMuscle_get_default_fiber_length__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_default_fiber_length() {
    return new SWIGTYPE_p_double(opensimModelJNI.Millard2012AccelerationMuscle_upd_default_fiber_length__SWIG_1(swigCPtr, this), false);
  }

  public void set_default_fiber_length(double value) {
    opensimModelJNI.Millard2012AccelerationMuscle_set_default_fiber_length__SWIG_1(swigCPtr, this, value);
  }

  public void setPropertyIndex_default_fiber_velocity(SWIGTYPE_p_PropertyIndex value) {
    opensimModelJNI.Millard2012AccelerationMuscle_PropertyIndex_default_fiber_velocity_set(swigCPtr, this, SWIGTYPE_p_PropertyIndex.getCPtr(value));
  }

  public SWIGTYPE_p_PropertyIndex getPropertyIndex_default_fiber_velocity() {
    return new SWIGTYPE_p_PropertyIndex(opensimModelJNI.Millard2012AccelerationMuscle_PropertyIndex_default_fiber_velocity_get(swigCPtr, this), true);
  }

  public void copyProperty_default_fiber_velocity(Millard2012AccelerationMuscle source) {
    opensimModelJNI.Millard2012AccelerationMuscle_copyProperty_default_fiber_velocity(swigCPtr, this, Millard2012AccelerationMuscle.getCPtr(source), source);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_double_t getProperty_default_fiber_velocity() {
    return new SWIGTYPE_p_OpenSim__PropertyT_double_t(opensimModelJNI.Millard2012AccelerationMuscle_getProperty_default_fiber_velocity(swigCPtr, this), false);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_double_t updProperty_default_fiber_velocity() {
    return new SWIGTYPE_p_OpenSim__PropertyT_double_t(opensimModelJNI.Millard2012AccelerationMuscle_updProperty_default_fiber_velocity(swigCPtr, this), false);
  }

  public double get_default_fiber_velocity(int i) {
    return opensimModelJNI.Millard2012AccelerationMuscle_get_default_fiber_velocity__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_default_fiber_velocity(int i) {
    return new SWIGTYPE_p_double(opensimModelJNI.Millard2012AccelerationMuscle_upd_default_fiber_velocity__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_default_fiber_velocity(int i, double value) {
    opensimModelJNI.Millard2012AccelerationMuscle_set_default_fiber_velocity__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_default_fiber_velocity(double value) {
    return opensimModelJNI.Millard2012AccelerationMuscle_append_default_fiber_velocity(swigCPtr, this, value);
  }

  public void constructProperty_default_fiber_velocity(double initValue) {
    opensimModelJNI.Millard2012AccelerationMuscle_constructProperty_default_fiber_velocity(swigCPtr, this, initValue);
  }

  public double get_default_fiber_velocity() {
    return opensimModelJNI.Millard2012AccelerationMuscle_get_default_fiber_velocity__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_default_fiber_velocity() {
    return new SWIGTYPE_p_double(opensimModelJNI.Millard2012AccelerationMuscle_upd_default_fiber_velocity__SWIG_1(swigCPtr, this), false);
  }

  public void set_default_fiber_velocity(double value) {
    opensimModelJNI.Millard2012AccelerationMuscle_set_default_fiber_velocity__SWIG_1(swigCPtr, this, value);
  }

  public void setPropertyIndex_MuscleFirstOrderActivationDynamicModel(SWIGTYPE_p_PropertyIndex value) {
    opensimModelJNI.Millard2012AccelerationMuscle_PropertyIndex_MuscleFirstOrderActivationDynamicModel_set(swigCPtr, this, SWIGTYPE_p_PropertyIndex.getCPtr(value));
  }

  public SWIGTYPE_p_PropertyIndex getPropertyIndex_MuscleFirstOrderActivationDynamicModel() {
    return new SWIGTYPE_p_PropertyIndex(opensimModelJNI.Millard2012AccelerationMuscle_PropertyIndex_MuscleFirstOrderActivationDynamicModel_get(swigCPtr, this), true);
  }

  public void copyProperty_MuscleFirstOrderActivationDynamicModel(Millard2012AccelerationMuscle source) {
    opensimModelJNI.Millard2012AccelerationMuscle_copyProperty_MuscleFirstOrderActivationDynamicModel(swigCPtr, this, Millard2012AccelerationMuscle.getCPtr(source), source);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_MuscleFirstOrderActivationDynamicModel_t getProperty_MuscleFirstOrderActivationDynamicModel() {
    return new SWIGTYPE_p_OpenSim__PropertyT_MuscleFirstOrderActivationDynamicModel_t(opensimModelJNI.Millard2012AccelerationMuscle_getProperty_MuscleFirstOrderActivationDynamicModel(swigCPtr, this), false);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_MuscleFirstOrderActivationDynamicModel_t updProperty_MuscleFirstOrderActivationDynamicModel() {
    return new SWIGTYPE_p_OpenSim__PropertyT_MuscleFirstOrderActivationDynamicModel_t(opensimModelJNI.Millard2012AccelerationMuscle_updProperty_MuscleFirstOrderActivationDynamicModel(swigCPtr, this), false);
  }

  public SWIGTYPE_p_MuscleFirstOrderActivationDynamicModel get_MuscleFirstOrderActivationDynamicModel(int i) {
    return new SWIGTYPE_p_MuscleFirstOrderActivationDynamicModel(opensimModelJNI.Millard2012AccelerationMuscle_get_MuscleFirstOrderActivationDynamicModel__SWIG_0(swigCPtr, this, i), false);
  }

  public SWIGTYPE_p_MuscleFirstOrderActivationDynamicModel upd_MuscleFirstOrderActivationDynamicModel(int i) {
    return new SWIGTYPE_p_MuscleFirstOrderActivationDynamicModel(opensimModelJNI.Millard2012AccelerationMuscle_upd_MuscleFirstOrderActivationDynamicModel__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_MuscleFirstOrderActivationDynamicModel(int i, SWIGTYPE_p_MuscleFirstOrderActivationDynamicModel value) {
    opensimModelJNI.Millard2012AccelerationMuscle_set_MuscleFirstOrderActivationDynamicModel__SWIG_0(swigCPtr, this, i, SWIGTYPE_p_MuscleFirstOrderActivationDynamicModel.getCPtr(value));
  }

  public int append_MuscleFirstOrderActivationDynamicModel(SWIGTYPE_p_MuscleFirstOrderActivationDynamicModel value) {
    return opensimModelJNI.Millard2012AccelerationMuscle_append_MuscleFirstOrderActivationDynamicModel(swigCPtr, this, SWIGTYPE_p_MuscleFirstOrderActivationDynamicModel.getCPtr(value));
  }

  public void constructProperty_MuscleFirstOrderActivationDynamicModel(SWIGTYPE_p_MuscleFirstOrderActivationDynamicModel initValue) {
    opensimModelJNI.Millard2012AccelerationMuscle_constructProperty_MuscleFirstOrderActivationDynamicModel(swigCPtr, this, SWIGTYPE_p_MuscleFirstOrderActivationDynamicModel.getCPtr(initValue));
  }

  public SWIGTYPE_p_MuscleFirstOrderActivationDynamicModel get_MuscleFirstOrderActivationDynamicModel() {
    return new SWIGTYPE_p_MuscleFirstOrderActivationDynamicModel(opensimModelJNI.Millard2012AccelerationMuscle_get_MuscleFirstOrderActivationDynamicModel__SWIG_1(swigCPtr, this), false);
  }

  public SWIGTYPE_p_MuscleFirstOrderActivationDynamicModel upd_MuscleFirstOrderActivationDynamicModel() {
    return new SWIGTYPE_p_MuscleFirstOrderActivationDynamicModel(opensimModelJNI.Millard2012AccelerationMuscle_upd_MuscleFirstOrderActivationDynamicModel__SWIG_1(swigCPtr, this), false);
  }

  public void set_MuscleFirstOrderActivationDynamicModel(SWIGTYPE_p_MuscleFirstOrderActivationDynamicModel value) {
    opensimModelJNI.Millard2012AccelerationMuscle_set_MuscleFirstOrderActivationDynamicModel__SWIG_1(swigCPtr, this, SWIGTYPE_p_MuscleFirstOrderActivationDynamicModel.getCPtr(value));
  }

  public void setPropertyIndex_ActiveForceLengthCurve(SWIGTYPE_p_PropertyIndex value) {
    opensimModelJNI.Millard2012AccelerationMuscle_PropertyIndex_ActiveForceLengthCurve_set(swigCPtr, this, SWIGTYPE_p_PropertyIndex.getCPtr(value));
  }

  public SWIGTYPE_p_PropertyIndex getPropertyIndex_ActiveForceLengthCurve() {
    return new SWIGTYPE_p_PropertyIndex(opensimModelJNI.Millard2012AccelerationMuscle_PropertyIndex_ActiveForceLengthCurve_get(swigCPtr, this), true);
  }

  public void copyProperty_ActiveForceLengthCurve(Millard2012AccelerationMuscle source) {
    opensimModelJNI.Millard2012AccelerationMuscle_copyProperty_ActiveForceLengthCurve(swigCPtr, this, Millard2012AccelerationMuscle.getCPtr(source), source);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_OpenSim__ActiveForceLengthCurve_t getProperty_ActiveForceLengthCurve() {
    return new SWIGTYPE_p_OpenSim__PropertyT_OpenSim__ActiveForceLengthCurve_t(opensimModelJNI.Millard2012AccelerationMuscle_getProperty_ActiveForceLengthCurve(swigCPtr, this), false);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_OpenSim__ActiveForceLengthCurve_t updProperty_ActiveForceLengthCurve() {
    return new SWIGTYPE_p_OpenSim__PropertyT_OpenSim__ActiveForceLengthCurve_t(opensimModelJNI.Millard2012AccelerationMuscle_updProperty_ActiveForceLengthCurve(swigCPtr, this), false);
  }

  public ActiveForceLengthCurve get_ActiveForceLengthCurve(int i) {
    return new ActiveForceLengthCurve(opensimModelJNI.Millard2012AccelerationMuscle_get_ActiveForceLengthCurve__SWIG_0(swigCPtr, this, i), false);
  }

  public ActiveForceLengthCurve upd_ActiveForceLengthCurve(int i) {
    return new ActiveForceLengthCurve(opensimModelJNI.Millard2012AccelerationMuscle_upd_ActiveForceLengthCurve__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_ActiveForceLengthCurve(int i, ActiveForceLengthCurve value) {
    opensimModelJNI.Millard2012AccelerationMuscle_set_ActiveForceLengthCurve__SWIG_0(swigCPtr, this, i, ActiveForceLengthCurve.getCPtr(value), value);
  }

  public int append_ActiveForceLengthCurve(ActiveForceLengthCurve value) {
    return opensimModelJNI.Millard2012AccelerationMuscle_append_ActiveForceLengthCurve(swigCPtr, this, ActiveForceLengthCurve.getCPtr(value), value);
  }

  public void constructProperty_ActiveForceLengthCurve(ActiveForceLengthCurve initValue) {
    opensimModelJNI.Millard2012AccelerationMuscle_constructProperty_ActiveForceLengthCurve(swigCPtr, this, ActiveForceLengthCurve.getCPtr(initValue), initValue);
  }

  public ActiveForceLengthCurve get_ActiveForceLengthCurve() {
    return new ActiveForceLengthCurve(opensimModelJNI.Millard2012AccelerationMuscle_get_ActiveForceLengthCurve__SWIG_1(swigCPtr, this), false);
  }

  public ActiveForceLengthCurve upd_ActiveForceLengthCurve() {
    return new ActiveForceLengthCurve(opensimModelJNI.Millard2012AccelerationMuscle_upd_ActiveForceLengthCurve__SWIG_1(swigCPtr, this), false);
  }

  public void set_ActiveForceLengthCurve(ActiveForceLengthCurve value) {
    opensimModelJNI.Millard2012AccelerationMuscle_set_ActiveForceLengthCurve__SWIG_1(swigCPtr, this, ActiveForceLengthCurve.getCPtr(value), value);
  }

  public void setPropertyIndex_ForceVelocityCurve(SWIGTYPE_p_PropertyIndex value) {
    opensimModelJNI.Millard2012AccelerationMuscle_PropertyIndex_ForceVelocityCurve_set(swigCPtr, this, SWIGTYPE_p_PropertyIndex.getCPtr(value));
  }

  public SWIGTYPE_p_PropertyIndex getPropertyIndex_ForceVelocityCurve() {
    return new SWIGTYPE_p_PropertyIndex(opensimModelJNI.Millard2012AccelerationMuscle_PropertyIndex_ForceVelocityCurve_get(swigCPtr, this), true);
  }

  public void copyProperty_ForceVelocityCurve(Millard2012AccelerationMuscle source) {
    opensimModelJNI.Millard2012AccelerationMuscle_copyProperty_ForceVelocityCurve(swigCPtr, this, Millard2012AccelerationMuscle.getCPtr(source), source);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_OpenSim__ForceVelocityCurve_t getProperty_ForceVelocityCurve() {
    return new SWIGTYPE_p_OpenSim__PropertyT_OpenSim__ForceVelocityCurve_t(opensimModelJNI.Millard2012AccelerationMuscle_getProperty_ForceVelocityCurve(swigCPtr, this), false);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_OpenSim__ForceVelocityCurve_t updProperty_ForceVelocityCurve() {
    return new SWIGTYPE_p_OpenSim__PropertyT_OpenSim__ForceVelocityCurve_t(opensimModelJNI.Millard2012AccelerationMuscle_updProperty_ForceVelocityCurve(swigCPtr, this), false);
  }

  public ForceVelocityCurve get_ForceVelocityCurve(int i) {
    return new ForceVelocityCurve(opensimModelJNI.Millard2012AccelerationMuscle_get_ForceVelocityCurve__SWIG_0(swigCPtr, this, i), false);
  }

  public ForceVelocityCurve upd_ForceVelocityCurve(int i) {
    return new ForceVelocityCurve(opensimModelJNI.Millard2012AccelerationMuscle_upd_ForceVelocityCurve__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_ForceVelocityCurve(int i, ForceVelocityCurve value) {
    opensimModelJNI.Millard2012AccelerationMuscle_set_ForceVelocityCurve__SWIG_0(swigCPtr, this, i, ForceVelocityCurve.getCPtr(value), value);
  }

  public int append_ForceVelocityCurve(ForceVelocityCurve value) {
    return opensimModelJNI.Millard2012AccelerationMuscle_append_ForceVelocityCurve(swigCPtr, this, ForceVelocityCurve.getCPtr(value), value);
  }

  public void constructProperty_ForceVelocityCurve(ForceVelocityCurve initValue) {
    opensimModelJNI.Millard2012AccelerationMuscle_constructProperty_ForceVelocityCurve(swigCPtr, this, ForceVelocityCurve.getCPtr(initValue), initValue);
  }

  public ForceVelocityCurve get_ForceVelocityCurve() {
    return new ForceVelocityCurve(opensimModelJNI.Millard2012AccelerationMuscle_get_ForceVelocityCurve__SWIG_1(swigCPtr, this), false);
  }

  public ForceVelocityCurve upd_ForceVelocityCurve() {
    return new ForceVelocityCurve(opensimModelJNI.Millard2012AccelerationMuscle_upd_ForceVelocityCurve__SWIG_1(swigCPtr, this), false);
  }

  public void set_ForceVelocityCurve(ForceVelocityCurve value) {
    opensimModelJNI.Millard2012AccelerationMuscle_set_ForceVelocityCurve__SWIG_1(swigCPtr, this, ForceVelocityCurve.getCPtr(value), value);
  }

  public void setPropertyIndex_FiberForceLengthCurve(SWIGTYPE_p_PropertyIndex value) {
    opensimModelJNI.Millard2012AccelerationMuscle_PropertyIndex_FiberForceLengthCurve_set(swigCPtr, this, SWIGTYPE_p_PropertyIndex.getCPtr(value));
  }

  public SWIGTYPE_p_PropertyIndex getPropertyIndex_FiberForceLengthCurve() {
    return new SWIGTYPE_p_PropertyIndex(opensimModelJNI.Millard2012AccelerationMuscle_PropertyIndex_FiberForceLengthCurve_get(swigCPtr, this), true);
  }

  public void copyProperty_FiberForceLengthCurve(Millard2012AccelerationMuscle source) {
    opensimModelJNI.Millard2012AccelerationMuscle_copyProperty_FiberForceLengthCurve(swigCPtr, this, Millard2012AccelerationMuscle.getCPtr(source), source);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_OpenSim__FiberForceLengthCurve_t getProperty_FiberForceLengthCurve() {
    return new SWIGTYPE_p_OpenSim__PropertyT_OpenSim__FiberForceLengthCurve_t(opensimModelJNI.Millard2012AccelerationMuscle_getProperty_FiberForceLengthCurve(swigCPtr, this), false);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_OpenSim__FiberForceLengthCurve_t updProperty_FiberForceLengthCurve() {
    return new SWIGTYPE_p_OpenSim__PropertyT_OpenSim__FiberForceLengthCurve_t(opensimModelJNI.Millard2012AccelerationMuscle_updProperty_FiberForceLengthCurve(swigCPtr, this), false);
  }

  public FiberForceLengthCurve get_FiberForceLengthCurve(int i) {
    return new FiberForceLengthCurve(opensimModelJNI.Millard2012AccelerationMuscle_get_FiberForceLengthCurve__SWIG_0(swigCPtr, this, i), false);
  }

  public FiberForceLengthCurve upd_FiberForceLengthCurve(int i) {
    return new FiberForceLengthCurve(opensimModelJNI.Millard2012AccelerationMuscle_upd_FiberForceLengthCurve__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_FiberForceLengthCurve(int i, FiberForceLengthCurve value) {
    opensimModelJNI.Millard2012AccelerationMuscle_set_FiberForceLengthCurve__SWIG_0(swigCPtr, this, i, FiberForceLengthCurve.getCPtr(value), value);
  }

  public int append_FiberForceLengthCurve(FiberForceLengthCurve value) {
    return opensimModelJNI.Millard2012AccelerationMuscle_append_FiberForceLengthCurve(swigCPtr, this, FiberForceLengthCurve.getCPtr(value), value);
  }

  public void constructProperty_FiberForceLengthCurve(FiberForceLengthCurve initValue) {
    opensimModelJNI.Millard2012AccelerationMuscle_constructProperty_FiberForceLengthCurve(swigCPtr, this, FiberForceLengthCurve.getCPtr(initValue), initValue);
  }

  public FiberForceLengthCurve get_FiberForceLengthCurve() {
    return new FiberForceLengthCurve(opensimModelJNI.Millard2012AccelerationMuscle_get_FiberForceLengthCurve__SWIG_1(swigCPtr, this), false);
  }

  public FiberForceLengthCurve upd_FiberForceLengthCurve() {
    return new FiberForceLengthCurve(opensimModelJNI.Millard2012AccelerationMuscle_upd_FiberForceLengthCurve__SWIG_1(swigCPtr, this), false);
  }

  public void set_FiberForceLengthCurve(FiberForceLengthCurve value) {
    opensimModelJNI.Millard2012AccelerationMuscle_set_FiberForceLengthCurve__SWIG_1(swigCPtr, this, FiberForceLengthCurve.getCPtr(value), value);
  }

  public void setPropertyIndex_TendonForceLengthCurve(SWIGTYPE_p_PropertyIndex value) {
    opensimModelJNI.Millard2012AccelerationMuscle_PropertyIndex_TendonForceLengthCurve_set(swigCPtr, this, SWIGTYPE_p_PropertyIndex.getCPtr(value));
  }

  public SWIGTYPE_p_PropertyIndex getPropertyIndex_TendonForceLengthCurve() {
    return new SWIGTYPE_p_PropertyIndex(opensimModelJNI.Millard2012AccelerationMuscle_PropertyIndex_TendonForceLengthCurve_get(swigCPtr, this), true);
  }

  public void copyProperty_TendonForceLengthCurve(Millard2012AccelerationMuscle source) {
    opensimModelJNI.Millard2012AccelerationMuscle_copyProperty_TendonForceLengthCurve(swigCPtr, this, Millard2012AccelerationMuscle.getCPtr(source), source);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_OpenSim__TendonForceLengthCurve_t getProperty_TendonForceLengthCurve() {
    return new SWIGTYPE_p_OpenSim__PropertyT_OpenSim__TendonForceLengthCurve_t(opensimModelJNI.Millard2012AccelerationMuscle_getProperty_TendonForceLengthCurve(swigCPtr, this), false);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_OpenSim__TendonForceLengthCurve_t updProperty_TendonForceLengthCurve() {
    return new SWIGTYPE_p_OpenSim__PropertyT_OpenSim__TendonForceLengthCurve_t(opensimModelJNI.Millard2012AccelerationMuscle_updProperty_TendonForceLengthCurve(swigCPtr, this), false);
  }

  public TendonForceLengthCurve get_TendonForceLengthCurve(int i) {
    return new TendonForceLengthCurve(opensimModelJNI.Millard2012AccelerationMuscle_get_TendonForceLengthCurve__SWIG_0(swigCPtr, this, i), false);
  }

  public TendonForceLengthCurve upd_TendonForceLengthCurve(int i) {
    return new TendonForceLengthCurve(opensimModelJNI.Millard2012AccelerationMuscle_upd_TendonForceLengthCurve__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_TendonForceLengthCurve(int i, TendonForceLengthCurve value) {
    opensimModelJNI.Millard2012AccelerationMuscle_set_TendonForceLengthCurve__SWIG_0(swigCPtr, this, i, TendonForceLengthCurve.getCPtr(value), value);
  }

  public int append_TendonForceLengthCurve(TendonForceLengthCurve value) {
    return opensimModelJNI.Millard2012AccelerationMuscle_append_TendonForceLengthCurve(swigCPtr, this, TendonForceLengthCurve.getCPtr(value), value);
  }

  public void constructProperty_TendonForceLengthCurve(TendonForceLengthCurve initValue) {
    opensimModelJNI.Millard2012AccelerationMuscle_constructProperty_TendonForceLengthCurve(swigCPtr, this, TendonForceLengthCurve.getCPtr(initValue), initValue);
  }

  public TendonForceLengthCurve get_TendonForceLengthCurve() {
    return new TendonForceLengthCurve(opensimModelJNI.Millard2012AccelerationMuscle_get_TendonForceLengthCurve__SWIG_1(swigCPtr, this), false);
  }

  public TendonForceLengthCurve upd_TendonForceLengthCurve() {
    return new TendonForceLengthCurve(opensimModelJNI.Millard2012AccelerationMuscle_upd_TendonForceLengthCurve__SWIG_1(swigCPtr, this), false);
  }

  public void set_TendonForceLengthCurve(TendonForceLengthCurve value) {
    opensimModelJNI.Millard2012AccelerationMuscle_set_TendonForceLengthCurve__SWIG_1(swigCPtr, this, TendonForceLengthCurve.getCPtr(value), value);
  }

  public void setPropertyIndex_FiberCompressiveForceLengthCurve(SWIGTYPE_p_PropertyIndex value) {
    opensimModelJNI.Millard2012AccelerationMuscle_PropertyIndex_FiberCompressiveForceLengthCurve_set(swigCPtr, this, SWIGTYPE_p_PropertyIndex.getCPtr(value));
  }

  public SWIGTYPE_p_PropertyIndex getPropertyIndex_FiberCompressiveForceLengthCurve() {
    return new SWIGTYPE_p_PropertyIndex(opensimModelJNI.Millard2012AccelerationMuscle_PropertyIndex_FiberCompressiveForceLengthCurve_get(swigCPtr, this), true);
  }

  public void copyProperty_FiberCompressiveForceLengthCurve(Millard2012AccelerationMuscle source) {
    opensimModelJNI.Millard2012AccelerationMuscle_copyProperty_FiberCompressiveForceLengthCurve(swigCPtr, this, Millard2012AccelerationMuscle.getCPtr(source), source);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_OpenSim__FiberCompressiveForceLengthCurve_t getProperty_FiberCompressiveForceLengthCurve() {
    return new SWIGTYPE_p_OpenSim__PropertyT_OpenSim__FiberCompressiveForceLengthCurve_t(opensimModelJNI.Millard2012AccelerationMuscle_getProperty_FiberCompressiveForceLengthCurve(swigCPtr, this), false);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_OpenSim__FiberCompressiveForceLengthCurve_t updProperty_FiberCompressiveForceLengthCurve() {
    return new SWIGTYPE_p_OpenSim__PropertyT_OpenSim__FiberCompressiveForceLengthCurve_t(opensimModelJNI.Millard2012AccelerationMuscle_updProperty_FiberCompressiveForceLengthCurve(swigCPtr, this), false);
  }

  public FiberCompressiveForceLengthCurve get_FiberCompressiveForceLengthCurve(int i) {
    return new FiberCompressiveForceLengthCurve(opensimModelJNI.Millard2012AccelerationMuscle_get_FiberCompressiveForceLengthCurve__SWIG_0(swigCPtr, this, i), false);
  }

  public FiberCompressiveForceLengthCurve upd_FiberCompressiveForceLengthCurve(int i) {
    return new FiberCompressiveForceLengthCurve(opensimModelJNI.Millard2012AccelerationMuscle_upd_FiberCompressiveForceLengthCurve__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_FiberCompressiveForceLengthCurve(int i, FiberCompressiveForceLengthCurve value) {
    opensimModelJNI.Millard2012AccelerationMuscle_set_FiberCompressiveForceLengthCurve__SWIG_0(swigCPtr, this, i, FiberCompressiveForceLengthCurve.getCPtr(value), value);
  }

  public int append_FiberCompressiveForceLengthCurve(FiberCompressiveForceLengthCurve value) {
    return opensimModelJNI.Millard2012AccelerationMuscle_append_FiberCompressiveForceLengthCurve(swigCPtr, this, FiberCompressiveForceLengthCurve.getCPtr(value), value);
  }

  public void constructProperty_FiberCompressiveForceLengthCurve(FiberCompressiveForceLengthCurve initValue) {
    opensimModelJNI.Millard2012AccelerationMuscle_constructProperty_FiberCompressiveForceLengthCurve(swigCPtr, this, FiberCompressiveForceLengthCurve.getCPtr(initValue), initValue);
  }

  public FiberCompressiveForceLengthCurve get_FiberCompressiveForceLengthCurve() {
    return new FiberCompressiveForceLengthCurve(opensimModelJNI.Millard2012AccelerationMuscle_get_FiberCompressiveForceLengthCurve__SWIG_1(swigCPtr, this), false);
  }

  public FiberCompressiveForceLengthCurve upd_FiberCompressiveForceLengthCurve() {
    return new FiberCompressiveForceLengthCurve(opensimModelJNI.Millard2012AccelerationMuscle_upd_FiberCompressiveForceLengthCurve__SWIG_1(swigCPtr, this), false);
  }

  public void set_FiberCompressiveForceLengthCurve(FiberCompressiveForceLengthCurve value) {
    opensimModelJNI.Millard2012AccelerationMuscle_set_FiberCompressiveForceLengthCurve__SWIG_1(swigCPtr, this, FiberCompressiveForceLengthCurve.getCPtr(value), value);
  }

  public void setPropertyIndex_FiberCompressiveForceCosPennationCurve(SWIGTYPE_p_PropertyIndex value) {
    opensimModelJNI.Millard2012AccelerationMuscle_PropertyIndex_FiberCompressiveForceCosPennationCurve_set(swigCPtr, this, SWIGTYPE_p_PropertyIndex.getCPtr(value));
  }

  public SWIGTYPE_p_PropertyIndex getPropertyIndex_FiberCompressiveForceCosPennationCurve() {
    return new SWIGTYPE_p_PropertyIndex(opensimModelJNI.Millard2012AccelerationMuscle_PropertyIndex_FiberCompressiveForceCosPennationCurve_get(swigCPtr, this), true);
  }

  public void copyProperty_FiberCompressiveForceCosPennationCurve(Millard2012AccelerationMuscle source) {
    opensimModelJNI.Millard2012AccelerationMuscle_copyProperty_FiberCompressiveForceCosPennationCurve(swigCPtr, this, Millard2012AccelerationMuscle.getCPtr(source), source);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_OpenSim__FiberCompressiveForceCosPennationCurve_t getProperty_FiberCompressiveForceCosPennationCurve() {
    return new SWIGTYPE_p_OpenSim__PropertyT_OpenSim__FiberCompressiveForceCosPennationCurve_t(opensimModelJNI.Millard2012AccelerationMuscle_getProperty_FiberCompressiveForceCosPennationCurve(swigCPtr, this), false);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_OpenSim__FiberCompressiveForceCosPennationCurve_t updProperty_FiberCompressiveForceCosPennationCurve() {
    return new SWIGTYPE_p_OpenSim__PropertyT_OpenSim__FiberCompressiveForceCosPennationCurve_t(opensimModelJNI.Millard2012AccelerationMuscle_updProperty_FiberCompressiveForceCosPennationCurve(swigCPtr, this), false);
  }

  public FiberCompressiveForceCosPennationCurve get_FiberCompressiveForceCosPennationCurve(int i) {
    return new FiberCompressiveForceCosPennationCurve(opensimModelJNI.Millard2012AccelerationMuscle_get_FiberCompressiveForceCosPennationCurve__SWIG_0(swigCPtr, this, i), false);
  }

  public FiberCompressiveForceCosPennationCurve upd_FiberCompressiveForceCosPennationCurve(int i) {
    return new FiberCompressiveForceCosPennationCurve(opensimModelJNI.Millard2012AccelerationMuscle_upd_FiberCompressiveForceCosPennationCurve__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_FiberCompressiveForceCosPennationCurve(int i, FiberCompressiveForceCosPennationCurve value) {
    opensimModelJNI.Millard2012AccelerationMuscle_set_FiberCompressiveForceCosPennationCurve__SWIG_0(swigCPtr, this, i, FiberCompressiveForceCosPennationCurve.getCPtr(value), value);
  }

  public int append_FiberCompressiveForceCosPennationCurve(FiberCompressiveForceCosPennationCurve value) {
    return opensimModelJNI.Millard2012AccelerationMuscle_append_FiberCompressiveForceCosPennationCurve(swigCPtr, this, FiberCompressiveForceCosPennationCurve.getCPtr(value), value);
  }

  public void constructProperty_FiberCompressiveForceCosPennationCurve(FiberCompressiveForceCosPennationCurve initValue) {
    opensimModelJNI.Millard2012AccelerationMuscle_constructProperty_FiberCompressiveForceCosPennationCurve(swigCPtr, this, FiberCompressiveForceCosPennationCurve.getCPtr(initValue), initValue);
  }

  public FiberCompressiveForceCosPennationCurve get_FiberCompressiveForceCosPennationCurve() {
    return new FiberCompressiveForceCosPennationCurve(opensimModelJNI.Millard2012AccelerationMuscle_get_FiberCompressiveForceCosPennationCurve__SWIG_1(swigCPtr, this), false);
  }

  public FiberCompressiveForceCosPennationCurve upd_FiberCompressiveForceCosPennationCurve() {
    return new FiberCompressiveForceCosPennationCurve(opensimModelJNI.Millard2012AccelerationMuscle_upd_FiberCompressiveForceCosPennationCurve__SWIG_1(swigCPtr, this), false);
  }

  public void set_FiberCompressiveForceCosPennationCurve(FiberCompressiveForceCosPennationCurve value) {
    opensimModelJNI.Millard2012AccelerationMuscle_set_FiberCompressiveForceCosPennationCurve__SWIG_1(swigCPtr, this, FiberCompressiveForceCosPennationCurve.getCPtr(value), value);
  }

  public void setPropertyIndex_fiber_damping(SWIGTYPE_p_PropertyIndex value) {
    opensimModelJNI.Millard2012AccelerationMuscle_PropertyIndex_fiber_damping_set(swigCPtr, this, SWIGTYPE_p_PropertyIndex.getCPtr(value));
  }

  public SWIGTYPE_p_PropertyIndex getPropertyIndex_fiber_damping() {
    return new SWIGTYPE_p_PropertyIndex(opensimModelJNI.Millard2012AccelerationMuscle_PropertyIndex_fiber_damping_get(swigCPtr, this), true);
  }

  public void copyProperty_fiber_damping(Millard2012AccelerationMuscle source) {
    opensimModelJNI.Millard2012AccelerationMuscle_copyProperty_fiber_damping(swigCPtr, this, Millard2012AccelerationMuscle.getCPtr(source), source);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_double_t getProperty_fiber_damping() {
    return new SWIGTYPE_p_OpenSim__PropertyT_double_t(opensimModelJNI.Millard2012AccelerationMuscle_getProperty_fiber_damping(swigCPtr, this), false);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_double_t updProperty_fiber_damping() {
    return new SWIGTYPE_p_OpenSim__PropertyT_double_t(opensimModelJNI.Millard2012AccelerationMuscle_updProperty_fiber_damping(swigCPtr, this), false);
  }

  public double get_fiber_damping(int i) {
    return opensimModelJNI.Millard2012AccelerationMuscle_get_fiber_damping__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_fiber_damping(int i) {
    return new SWIGTYPE_p_double(opensimModelJNI.Millard2012AccelerationMuscle_upd_fiber_damping__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_fiber_damping(int i, double value) {
    opensimModelJNI.Millard2012AccelerationMuscle_set_fiber_damping__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_fiber_damping(double value) {
    return opensimModelJNI.Millard2012AccelerationMuscle_append_fiber_damping(swigCPtr, this, value);
  }

  public void constructProperty_fiber_damping(double initValue) {
    opensimModelJNI.Millard2012AccelerationMuscle_constructProperty_fiber_damping(swigCPtr, this, initValue);
  }

  public double get_fiber_damping() {
    return opensimModelJNI.Millard2012AccelerationMuscle_get_fiber_damping__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_fiber_damping() {
    return new SWIGTYPE_p_double(opensimModelJNI.Millard2012AccelerationMuscle_upd_fiber_damping__SWIG_1(swigCPtr, this), false);
  }

  public void set_fiber_damping(double value) {
    opensimModelJNI.Millard2012AccelerationMuscle_set_fiber_damping__SWIG_1(swigCPtr, this, value);
  }

  public void setPropertyIndex_fiber_force_length_damping(SWIGTYPE_p_PropertyIndex value) {
    opensimModelJNI.Millard2012AccelerationMuscle_PropertyIndex_fiber_force_length_damping_set(swigCPtr, this, SWIGTYPE_p_PropertyIndex.getCPtr(value));
  }

  public SWIGTYPE_p_PropertyIndex getPropertyIndex_fiber_force_length_damping() {
    return new SWIGTYPE_p_PropertyIndex(opensimModelJNI.Millard2012AccelerationMuscle_PropertyIndex_fiber_force_length_damping_get(swigCPtr, this), true);
  }

  public void copyProperty_fiber_force_length_damping(Millard2012AccelerationMuscle source) {
    opensimModelJNI.Millard2012AccelerationMuscle_copyProperty_fiber_force_length_damping(swigCPtr, this, Millard2012AccelerationMuscle.getCPtr(source), source);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_double_t getProperty_fiber_force_length_damping() {
    return new SWIGTYPE_p_OpenSim__PropertyT_double_t(opensimModelJNI.Millard2012AccelerationMuscle_getProperty_fiber_force_length_damping(swigCPtr, this), false);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_double_t updProperty_fiber_force_length_damping() {
    return new SWIGTYPE_p_OpenSim__PropertyT_double_t(opensimModelJNI.Millard2012AccelerationMuscle_updProperty_fiber_force_length_damping(swigCPtr, this), false);
  }

  public double get_fiber_force_length_damping(int i) {
    return opensimModelJNI.Millard2012AccelerationMuscle_get_fiber_force_length_damping__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_fiber_force_length_damping(int i) {
    return new SWIGTYPE_p_double(opensimModelJNI.Millard2012AccelerationMuscle_upd_fiber_force_length_damping__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_fiber_force_length_damping(int i, double value) {
    opensimModelJNI.Millard2012AccelerationMuscle_set_fiber_force_length_damping__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_fiber_force_length_damping(double value) {
    return opensimModelJNI.Millard2012AccelerationMuscle_append_fiber_force_length_damping(swigCPtr, this, value);
  }

  public void constructProperty_fiber_force_length_damping(double initValue) {
    opensimModelJNI.Millard2012AccelerationMuscle_constructProperty_fiber_force_length_damping(swigCPtr, this, initValue);
  }

  public double get_fiber_force_length_damping() {
    return opensimModelJNI.Millard2012AccelerationMuscle_get_fiber_force_length_damping__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_fiber_force_length_damping() {
    return new SWIGTYPE_p_double(opensimModelJNI.Millard2012AccelerationMuscle_upd_fiber_force_length_damping__SWIG_1(swigCPtr, this), false);
  }

  public void set_fiber_force_length_damping(double value) {
    opensimModelJNI.Millard2012AccelerationMuscle_set_fiber_force_length_damping__SWIG_1(swigCPtr, this, value);
  }

  public void setPropertyIndex_fiber_compressive_force_length_damping(SWIGTYPE_p_PropertyIndex value) {
    opensimModelJNI.Millard2012AccelerationMuscle_PropertyIndex_fiber_compressive_force_length_damping_set(swigCPtr, this, SWIGTYPE_p_PropertyIndex.getCPtr(value));
  }

  public SWIGTYPE_p_PropertyIndex getPropertyIndex_fiber_compressive_force_length_damping() {
    return new SWIGTYPE_p_PropertyIndex(opensimModelJNI.Millard2012AccelerationMuscle_PropertyIndex_fiber_compressive_force_length_damping_get(swigCPtr, this), true);
  }

  public void copyProperty_fiber_compressive_force_length_damping(Millard2012AccelerationMuscle source) {
    opensimModelJNI.Millard2012AccelerationMuscle_copyProperty_fiber_compressive_force_length_damping(swigCPtr, this, Millard2012AccelerationMuscle.getCPtr(source), source);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_double_t getProperty_fiber_compressive_force_length_damping() {
    return new SWIGTYPE_p_OpenSim__PropertyT_double_t(opensimModelJNI.Millard2012AccelerationMuscle_getProperty_fiber_compressive_force_length_damping(swigCPtr, this), false);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_double_t updProperty_fiber_compressive_force_length_damping() {
    return new SWIGTYPE_p_OpenSim__PropertyT_double_t(opensimModelJNI.Millard2012AccelerationMuscle_updProperty_fiber_compressive_force_length_damping(swigCPtr, this), false);
  }

  public double get_fiber_compressive_force_length_damping(int i) {
    return opensimModelJNI.Millard2012AccelerationMuscle_get_fiber_compressive_force_length_damping__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_fiber_compressive_force_length_damping(int i) {
    return new SWIGTYPE_p_double(opensimModelJNI.Millard2012AccelerationMuscle_upd_fiber_compressive_force_length_damping__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_fiber_compressive_force_length_damping(int i, double value) {
    opensimModelJNI.Millard2012AccelerationMuscle_set_fiber_compressive_force_length_damping__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_fiber_compressive_force_length_damping(double value) {
    return opensimModelJNI.Millard2012AccelerationMuscle_append_fiber_compressive_force_length_damping(swigCPtr, this, value);
  }

  public void constructProperty_fiber_compressive_force_length_damping(double initValue) {
    opensimModelJNI.Millard2012AccelerationMuscle_constructProperty_fiber_compressive_force_length_damping(swigCPtr, this, initValue);
  }

  public double get_fiber_compressive_force_length_damping() {
    return opensimModelJNI.Millard2012AccelerationMuscle_get_fiber_compressive_force_length_damping__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_fiber_compressive_force_length_damping() {
    return new SWIGTYPE_p_double(opensimModelJNI.Millard2012AccelerationMuscle_upd_fiber_compressive_force_length_damping__SWIG_1(swigCPtr, this), false);
  }

  public void set_fiber_compressive_force_length_damping(double value) {
    opensimModelJNI.Millard2012AccelerationMuscle_set_fiber_compressive_force_length_damping__SWIG_1(swigCPtr, this, value);
  }

  public void setPropertyIndex_fiber_compressive_force_cos_pennation_damping(SWIGTYPE_p_PropertyIndex value) {
    opensimModelJNI.Millard2012AccelerationMuscle_PropertyIndex_fiber_compressive_force_cos_pennation_damping_set(swigCPtr, this, SWIGTYPE_p_PropertyIndex.getCPtr(value));
  }

  public SWIGTYPE_p_PropertyIndex getPropertyIndex_fiber_compressive_force_cos_pennation_damping() {
    return new SWIGTYPE_p_PropertyIndex(opensimModelJNI.Millard2012AccelerationMuscle_PropertyIndex_fiber_compressive_force_cos_pennation_damping_get(swigCPtr, this), true);
  }

  public void copyProperty_fiber_compressive_force_cos_pennation_damping(Millard2012AccelerationMuscle source) {
    opensimModelJNI.Millard2012AccelerationMuscle_copyProperty_fiber_compressive_force_cos_pennation_damping(swigCPtr, this, Millard2012AccelerationMuscle.getCPtr(source), source);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_double_t getProperty_fiber_compressive_force_cos_pennation_damping() {
    return new SWIGTYPE_p_OpenSim__PropertyT_double_t(opensimModelJNI.Millard2012AccelerationMuscle_getProperty_fiber_compressive_force_cos_pennation_damping(swigCPtr, this), false);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_double_t updProperty_fiber_compressive_force_cos_pennation_damping() {
    return new SWIGTYPE_p_OpenSim__PropertyT_double_t(opensimModelJNI.Millard2012AccelerationMuscle_updProperty_fiber_compressive_force_cos_pennation_damping(swigCPtr, this), false);
  }

  public double get_fiber_compressive_force_cos_pennation_damping(int i) {
    return opensimModelJNI.Millard2012AccelerationMuscle_get_fiber_compressive_force_cos_pennation_damping__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_fiber_compressive_force_cos_pennation_damping(int i) {
    return new SWIGTYPE_p_double(opensimModelJNI.Millard2012AccelerationMuscle_upd_fiber_compressive_force_cos_pennation_damping__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_fiber_compressive_force_cos_pennation_damping(int i, double value) {
    opensimModelJNI.Millard2012AccelerationMuscle_set_fiber_compressive_force_cos_pennation_damping__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_fiber_compressive_force_cos_pennation_damping(double value) {
    return opensimModelJNI.Millard2012AccelerationMuscle_append_fiber_compressive_force_cos_pennation_damping(swigCPtr, this, value);
  }

  public void constructProperty_fiber_compressive_force_cos_pennation_damping(double initValue) {
    opensimModelJNI.Millard2012AccelerationMuscle_constructProperty_fiber_compressive_force_cos_pennation_damping(swigCPtr, this, initValue);
  }

  public double get_fiber_compressive_force_cos_pennation_damping() {
    return opensimModelJNI.Millard2012AccelerationMuscle_get_fiber_compressive_force_cos_pennation_damping__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_fiber_compressive_force_cos_pennation_damping() {
    return new SWIGTYPE_p_double(opensimModelJNI.Millard2012AccelerationMuscle_upd_fiber_compressive_force_cos_pennation_damping__SWIG_1(swigCPtr, this), false);
  }

  public void set_fiber_compressive_force_cos_pennation_damping(double value) {
    opensimModelJNI.Millard2012AccelerationMuscle_set_fiber_compressive_force_cos_pennation_damping__SWIG_1(swigCPtr, this, value);
  }

  public void setPropertyIndex_tendon_force_length_damping(SWIGTYPE_p_PropertyIndex value) {
    opensimModelJNI.Millard2012AccelerationMuscle_PropertyIndex_tendon_force_length_damping_set(swigCPtr, this, SWIGTYPE_p_PropertyIndex.getCPtr(value));
  }

  public SWIGTYPE_p_PropertyIndex getPropertyIndex_tendon_force_length_damping() {
    return new SWIGTYPE_p_PropertyIndex(opensimModelJNI.Millard2012AccelerationMuscle_PropertyIndex_tendon_force_length_damping_get(swigCPtr, this), true);
  }

  public void copyProperty_tendon_force_length_damping(Millard2012AccelerationMuscle source) {
    opensimModelJNI.Millard2012AccelerationMuscle_copyProperty_tendon_force_length_damping(swigCPtr, this, Millard2012AccelerationMuscle.getCPtr(source), source);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_double_t getProperty_tendon_force_length_damping() {
    return new SWIGTYPE_p_OpenSim__PropertyT_double_t(opensimModelJNI.Millard2012AccelerationMuscle_getProperty_tendon_force_length_damping(swigCPtr, this), false);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_double_t updProperty_tendon_force_length_damping() {
    return new SWIGTYPE_p_OpenSim__PropertyT_double_t(opensimModelJNI.Millard2012AccelerationMuscle_updProperty_tendon_force_length_damping(swigCPtr, this), false);
  }

  public double get_tendon_force_length_damping(int i) {
    return opensimModelJNI.Millard2012AccelerationMuscle_get_tendon_force_length_damping__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_tendon_force_length_damping(int i) {
    return new SWIGTYPE_p_double(opensimModelJNI.Millard2012AccelerationMuscle_upd_tendon_force_length_damping__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_tendon_force_length_damping(int i, double value) {
    opensimModelJNI.Millard2012AccelerationMuscle_set_tendon_force_length_damping__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_tendon_force_length_damping(double value) {
    return opensimModelJNI.Millard2012AccelerationMuscle_append_tendon_force_length_damping(swigCPtr, this, value);
  }

  public void constructProperty_tendon_force_length_damping(double initValue) {
    opensimModelJNI.Millard2012AccelerationMuscle_constructProperty_tendon_force_length_damping(swigCPtr, this, initValue);
  }

  public double get_tendon_force_length_damping() {
    return opensimModelJNI.Millard2012AccelerationMuscle_get_tendon_force_length_damping__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_tendon_force_length_damping() {
    return new SWIGTYPE_p_double(opensimModelJNI.Millard2012AccelerationMuscle_upd_tendon_force_length_damping__SWIG_1(swigCPtr, this), false);
  }

  public void set_tendon_force_length_damping(double value) {
    opensimModelJNI.Millard2012AccelerationMuscle_set_tendon_force_length_damping__SWIG_1(swigCPtr, this, value);
  }

  public void setPropertyIndex_mass(SWIGTYPE_p_PropertyIndex value) {
    opensimModelJNI.Millard2012AccelerationMuscle_PropertyIndex_mass_set(swigCPtr, this, SWIGTYPE_p_PropertyIndex.getCPtr(value));
  }

  public SWIGTYPE_p_PropertyIndex getPropertyIndex_mass() {
    return new SWIGTYPE_p_PropertyIndex(opensimModelJNI.Millard2012AccelerationMuscle_PropertyIndex_mass_get(swigCPtr, this), true);
  }

  public void copyProperty_mass(Millard2012AccelerationMuscle source) {
    opensimModelJNI.Millard2012AccelerationMuscle_copyProperty_mass(swigCPtr, this, Millard2012AccelerationMuscle.getCPtr(source), source);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_double_t getProperty_mass() {
    return new SWIGTYPE_p_OpenSim__PropertyT_double_t(opensimModelJNI.Millard2012AccelerationMuscle_getProperty_mass(swigCPtr, this), false);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_double_t updProperty_mass() {
    return new SWIGTYPE_p_OpenSim__PropertyT_double_t(opensimModelJNI.Millard2012AccelerationMuscle_updProperty_mass(swigCPtr, this), false);
  }

  public double get_mass(int i) {
    return opensimModelJNI.Millard2012AccelerationMuscle_get_mass__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_mass(int i) {
    return new SWIGTYPE_p_double(opensimModelJNI.Millard2012AccelerationMuscle_upd_mass__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_mass(int i, double value) {
    opensimModelJNI.Millard2012AccelerationMuscle_set_mass__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_mass(double value) {
    return opensimModelJNI.Millard2012AccelerationMuscle_append_mass(swigCPtr, this, value);
  }

  public void constructProperty_mass(double initValue) {
    opensimModelJNI.Millard2012AccelerationMuscle_constructProperty_mass(swigCPtr, this, initValue);
  }

  public double get_mass() {
    return opensimModelJNI.Millard2012AccelerationMuscle_get_mass__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_mass() {
    return new SWIGTYPE_p_double(opensimModelJNI.Millard2012AccelerationMuscle_upd_mass__SWIG_1(swigCPtr, this), false);
  }

  public void set_mass(double value) {
    opensimModelJNI.Millard2012AccelerationMuscle_set_mass__SWIG_1(swigCPtr, this, value);
  }

  public Millard2012AccelerationMuscle() {
    this(opensimModelJNI.new_Millard2012AccelerationMuscle__SWIG_0(), true);
  }

  public Millard2012AccelerationMuscle(String aName, double aMaxIsometricForce, double aOptimalFiberLength, double aTendonSlackLength, double aPennationAngle) {
    this(opensimModelJNI.new_Millard2012AccelerationMuscle__SWIG_1(aName, aMaxIsometricForce, aOptimalFiberLength, aTendonSlackLength, aPennationAngle), true);
  }

  public double getFiberCompressiveForceLengthMultiplier(State s) {
    return opensimModelJNI.Millard2012AccelerationMuscle_getFiberCompressiveForceLengthMultiplier(swigCPtr, this, State.getCPtr(s), s);
  }

  public double getFiberCompressiveForceCosPennationMultiplier(State s) {
    return opensimModelJNI.Millard2012AccelerationMuscle_getFiberCompressiveForceCosPennationMultiplier(swigCPtr, this, State.getCPtr(s), s);
  }

  public double getTendonForceMultiplier(State s) {
    return opensimModelJNI.Millard2012AccelerationMuscle_getTendonForceMultiplier(swigCPtr, this, State.getCPtr(s), s);
  }

  public double getMass() {
    return opensimModelJNI.Millard2012AccelerationMuscle_getMass(swigCPtr, this);
  }

  public SWIGTYPE_p_MuscleFirstOrderActivationDynamicModel getActivationModel() {
    return new SWIGTYPE_p_MuscleFirstOrderActivationDynamicModel(opensimModelJNI.Millard2012AccelerationMuscle_getActivationModel(swigCPtr, this), false);
  }

  public SWIGTYPE_p_MuscleFixedWidthPennationModel getPennationModel() {
    return new SWIGTYPE_p_MuscleFixedWidthPennationModel(opensimModelJNI.Millard2012AccelerationMuscle_getPennationModel(swigCPtr, this), false);
  }

  public ActiveForceLengthCurve getActiveForceLengthCurve() {
    return new ActiveForceLengthCurve(opensimModelJNI.Millard2012AccelerationMuscle_getActiveForceLengthCurve(swigCPtr, this), false);
  }

  public ForceVelocityCurve getForceVelocityCurve() {
    return new ForceVelocityCurve(opensimModelJNI.Millard2012AccelerationMuscle_getForceVelocityCurve(swigCPtr, this), false);
  }

  public FiberForceLengthCurve getFiberForceLengthCurve() {
    return new FiberForceLengthCurve(opensimModelJNI.Millard2012AccelerationMuscle_getFiberForceLengthCurve(swigCPtr, this), false);
  }

  public TendonForceLengthCurve getTendonForceLengthCurve() {
    return new TendonForceLengthCurve(opensimModelJNI.Millard2012AccelerationMuscle_getTendonForceLengthCurve(swigCPtr, this), false);
  }

  public FiberCompressiveForceLengthCurve getFiberCompressiveForceLengthCurve() {
    return new FiberCompressiveForceLengthCurve(opensimModelJNI.Millard2012AccelerationMuscle_getFiberCompressiveForceLengthCurve(swigCPtr, this), false);
  }

  public FiberCompressiveForceCosPennationCurve getFiberCompressiveForceCosPennationCurve() {
    return new FiberCompressiveForceCosPennationCurve(opensimModelJNI.Millard2012AccelerationMuscle_getFiberCompressiveForceCosPennationCurve(swigCPtr, this), false);
  }

  public double getFiberStiffnessAlongTendon(State s) {
    return opensimModelJNI.Millard2012AccelerationMuscle_getFiberStiffnessAlongTendon(swigCPtr, this, State.getCPtr(s), s);
  }

  public void setActivationModel(SWIGTYPE_p_MuscleFirstOrderActivationDynamicModel aActivationMdl) {
    opensimModelJNI.Millard2012AccelerationMuscle_setActivationModel(swigCPtr, this, SWIGTYPE_p_MuscleFirstOrderActivationDynamicModel.getCPtr(aActivationMdl));
  }

  public void setActiveForceLengthCurve(ActiveForceLengthCurve aActiveForceLengthCurve) {
    opensimModelJNI.Millard2012AccelerationMuscle_setActiveForceLengthCurve(swigCPtr, this, ActiveForceLengthCurve.getCPtr(aActiveForceLengthCurve), aActiveForceLengthCurve);
  }

  public void setForceVelocityCurve(ForceVelocityCurve aForceVelocityCurve) {
    opensimModelJNI.Millard2012AccelerationMuscle_setForceVelocityCurve(swigCPtr, this, ForceVelocityCurve.getCPtr(aForceVelocityCurve), aForceVelocityCurve);
  }

  public void setFiberForceLengthCurve(FiberForceLengthCurve aFiberForceLengthCurve) {
    opensimModelJNI.Millard2012AccelerationMuscle_setFiberForceLengthCurve(swigCPtr, this, FiberForceLengthCurve.getCPtr(aFiberForceLengthCurve), aFiberForceLengthCurve);
  }

  public void setTendonForceLengthCurve(TendonForceLengthCurve aTendonForceLengthCurve) {
    opensimModelJNI.Millard2012AccelerationMuscle_setTendonForceLengthCurve(swigCPtr, this, TendonForceLengthCurve.getCPtr(aTendonForceLengthCurve), aTendonForceLengthCurve);
  }

  public void setFiberCompressiveForceLengthCurve(FiberCompressiveForceLengthCurve aFiberCompressiveForceLengthCurve) {
    opensimModelJNI.Millard2012AccelerationMuscle_setFiberCompressiveForceLengthCurve(swigCPtr, this, FiberCompressiveForceLengthCurve.getCPtr(aFiberCompressiveForceLengthCurve), aFiberCompressiveForceLengthCurve);
  }

  public void setFiberCompressiveForceCosPennationCurve(FiberCompressiveForceCosPennationCurve aFiberCompressiveForceCosPennationCurve) {
    opensimModelJNI.Millard2012AccelerationMuscle_setFiberCompressiveForceCosPennationCurve(swigCPtr, this, FiberCompressiveForceCosPennationCurve.getCPtr(aFiberCompressiveForceCosPennationCurve), aFiberCompressiveForceCosPennationCurve);
  }

  public void setMass(double mass) {
    opensimModelJNI.Millard2012AccelerationMuscle_setMass(swigCPtr, this, mass);
  }

  public double getDefaultActivation() {
    return opensimModelJNI.Millard2012AccelerationMuscle_getDefaultActivation(swigCPtr, this);
  }

  public double getDefaultFiberLength() {
    return opensimModelJNI.Millard2012AccelerationMuscle_getDefaultFiberLength(swigCPtr, this);
  }

  public double getDefaultFiberVelocity() {
    return opensimModelJNI.Millard2012AccelerationMuscle_getDefaultFiberVelocity(swigCPtr, this);
  }

  public double getActivationRate(State s) {
    return opensimModelJNI.Millard2012AccelerationMuscle_getActivationRate(swigCPtr, this, State.getCPtr(s), s);
  }

  public double getFiberVelocity(State s) {
    return opensimModelJNI.Millard2012AccelerationMuscle_getFiberVelocity(swigCPtr, this, State.getCPtr(s), s);
  }

  public double getFiberAcceleration(State s) {
    return opensimModelJNI.Millard2012AccelerationMuscle_getFiberAcceleration(swigCPtr, this, State.getCPtr(s), s);
  }

  public void setDefaultActivation(double activation) {
    opensimModelJNI.Millard2012AccelerationMuscle_setDefaultActivation(swigCPtr, this, activation);
  }

  public void setDefaultFiberLength(double fiberLength) {
    opensimModelJNI.Millard2012AccelerationMuscle_setDefaultFiberLength(swigCPtr, this, fiberLength);
  }

  public void setDefaultFiberVelocity(double fiberVelocity) {
    opensimModelJNI.Millard2012AccelerationMuscle_setDefaultFiberVelocity(swigCPtr, this, fiberVelocity);
  }

  public void setActivation(State s, double activation) {
    opensimModelJNI.Millard2012AccelerationMuscle_setActivation(swigCPtr, this, State.getCPtr(s), s, activation);
  }

  public void setFiberLength(State s, double fiberLength) {
    opensimModelJNI.Millard2012AccelerationMuscle_setFiberLength(swigCPtr, this, State.getCPtr(s), s, fiberLength);
  }

  public void setFiberVelocity(State s, double fiberVelocity) {
    opensimModelJNI.Millard2012AccelerationMuscle_setFiberVelocity(swigCPtr, this, State.getCPtr(s), s, fiberVelocity);
  }

  public ArrayStr getStateVariableNames() {
    return new ArrayStr(opensimModelJNI.Millard2012AccelerationMuscle_getStateVariableNames(swigCPtr, this), true);
  }

  public int getStateVariableSystemIndex(String stateVariableName) {
    return opensimModelJNI.Millard2012AccelerationMuscle_getStateVariableSystemIndex(swigCPtr, this, stateVariableName);
  }

  public double computeActuation(State s) {
    return opensimModelJNI.Millard2012AccelerationMuscle_computeActuation(swigCPtr, this, State.getCPtr(s), s);
  }

  public void computeInitialFiberEquilibrium(State s) {
    opensimModelJNI.Millard2012AccelerationMuscle_computeInitialFiberEquilibrium(swigCPtr, this, State.getCPtr(s), s);
  }

  public double calcInextensibleTendonActiveFiberForce(State s, double aActivation) {
    return opensimModelJNI.Millard2012AccelerationMuscle_calcInextensibleTendonActiveFiberForce(swigCPtr, this, State.getCPtr(s), s, aActivation);
  }

  public double calcActiveFiberForceAlongTendon(double activation, double fiberLength, double fiberVelocity) {
    return opensimModelJNI.Millard2012AccelerationMuscle_calcActiveFiberForceAlongTendon(swigCPtr, this, activation, fiberLength, fiberVelocity);
  }

}
