/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class MovingPathPoint extends PathPoint {
  private transient long swigCPtr;

  public MovingPathPoint(long cPtr, boolean cMemoryOwn) {
    super(opensimModelSimulationJNI.MovingPathPoint_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(MovingPathPoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimModelSimulationJNI.delete_MovingPathPoint(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static MovingPathPoint safeDownCast(OpenSimObject obj) {
    long cPtr = opensimModelSimulationJNI.MovingPathPoint_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new MovingPathPoint(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimModelSimulationJNI.MovingPathPoint_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimModelSimulationJNI.MovingPathPoint_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimModelSimulationJNI.MovingPathPoint_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new MovingPathPoint(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimModelSimulationJNI.MovingPathPoint_getConcreteClassName(swigCPtr, this);
  }

  public MovingPathPoint() {
    this(opensimModelSimulationJNI.new_MovingPathPoint__SWIG_0(), true);
  }

  public MovingPathPoint(MovingPathPoint aPoint) {
    this(opensimModelSimulationJNI.new_MovingPathPoint__SWIG_1(MovingPathPoint.getCPtr(aPoint), aPoint), true);
  }

  public void copyData(MovingPathPoint aPoint) {
    opensimModelSimulationJNI.MovingPathPoint_copyData(swigCPtr, this, MovingPathPoint.getCPtr(aPoint), aPoint);
  }

  public void updateFromXMLNode(SWIGTYPE_p_SimTK__Xml__Element aNode, int versionNumber) {
    opensimModelSimulationJNI.MovingPathPoint_updateFromXMLNode(swigCPtr, this, SWIGTYPE_p_SimTK__Xml__Element.getCPtr(aNode), versionNumber);
  }

  public void init(PathPoint aPoint) {
    opensimModelSimulationJNI.MovingPathPoint_init(swigCPtr, this, PathPoint.getCPtr(aPoint), aPoint);
  }

  public Coordinate getXCoordinate() {
    long cPtr = opensimModelSimulationJNI.MovingPathPoint_getXCoordinate(swigCPtr, this);
    return (cPtr == 0) ? null : new Coordinate(cPtr, false);
  }

  public Coordinate getYCoordinate() {
    long cPtr = opensimModelSimulationJNI.MovingPathPoint_getYCoordinate(swigCPtr, this);
    return (cPtr == 0) ? null : new Coordinate(cPtr, false);
  }

  public Coordinate getZCoordinate() {
    long cPtr = opensimModelSimulationJNI.MovingPathPoint_getZCoordinate(swigCPtr, this);
    return (cPtr == 0) ? null : new Coordinate(cPtr, false);
  }

  public Vec3 getdPointdQ(State s) {
    return new Vec3(opensimModelSimulationJNI.MovingPathPoint_getdPointdQ(swigCPtr, this, State.getCPtr(s), s), true);
  }

  public String getXCoordinateName() {
    return opensimModelSimulationJNI.MovingPathPoint_getXCoordinateName(swigCPtr, this);
  }

  public String getYCoordinateName() {
    return opensimModelSimulationJNI.MovingPathPoint_getYCoordinateName(swigCPtr, this);
  }

  public String getZCoordinateName() {
    return opensimModelSimulationJNI.MovingPathPoint_getZCoordinateName(swigCPtr, this);
  }

  public Function getXFunction() {
    long cPtr = opensimModelSimulationJNI.MovingPathPoint_getXFunction(swigCPtr, this);
    return (cPtr == 0) ? null : new Function(cPtr, false);
  }

  public Function getYFunction() {
    long cPtr = opensimModelSimulationJNI.MovingPathPoint_getYFunction(swigCPtr, this);
    return (cPtr == 0) ? null : new Function(cPtr, false);
  }

  public Function getZFunction() {
    long cPtr = opensimModelSimulationJNI.MovingPathPoint_getZFunction(swigCPtr, this);
    return (cPtr == 0) ? null : new Function(cPtr, false);
  }

  public void scale(State s, Vec3 aScaleFactors) {
    opensimModelSimulationJNI.MovingPathPoint_scale(swigCPtr, this, State.getCPtr(s), s, Vec3.getCPtr(aScaleFactors), aScaleFactors);
  }

}
