/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class NoRegisteredDataAdapter extends OpenSimException {
  private transient long swigCPtr;

  public NoRegisteredDataAdapter(long cPtr, boolean cMemoryOwn) {
    super(opensimModelJNI.NoRegisteredDataAdapter_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(NoRegisteredDataAdapter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimModelJNI.delete_NoRegisteredDataAdapter(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public NoRegisteredDataAdapter(String file, long line, String func, String key) {
    this(opensimModelJNI.new_NoRegisteredDataAdapter(file, line, func, key), true);
  }

}
