/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public interface opensimModelConstants {
  public final static String GET_SYSTEM_INFO = opensimModelJNI.GET_SYSTEM_INFO_get();
  public final static String GET_COMPILER_INFO = opensimModelJNI.GET_COMPILER_INFO_get();
  public final static String GET_OS_NAME = opensimModelJNI.GET_OS_NAME_get();
  public final static String GET_OSIM_VERSION = opensimModelJNI.GET_OSIM_VERSION_get();
  public final static double SimTK_PI = opensimModelJNI.SimTK_PI_get();
  public final static double SimTK_E = opensimModelJNI.SimTK_E_get();
  public final static double SimTK_LN2 = opensimModelJNI.SimTK_LN2_get();
  public final static double SimTK_LN10 = opensimModelJNI.SimTK_LN10_get();
  public final static double SimTK_LOG2E = opensimModelJNI.SimTK_LOG2E_get();
  public final static double SimTK_LOG10E = opensimModelJNI.SimTK_LOG10E_get();
  public final static double SimTK_SQRT2 = opensimModelJNI.SimTK_SQRT2_get();
  public final static double SimTK_OOSQRT2 = opensimModelJNI.SimTK_OOSQRT2_get();
  public final static double SimTK_CBRT2 = opensimModelJNI.SimTK_CBRT2_get();
  public final static double SimTK_OOCBRT2 = opensimModelJNI.SimTK_OOCBRT2_get();
  public final static double SimTK_SIXRT2 = opensimModelJNI.SimTK_SIXRT2_get();
  public final static double SimTK_OOSIXRT2 = opensimModelJNI.SimTK_OOSIXRT2_get();
  public final static double SimTK_SQRT3 = opensimModelJNI.SimTK_SQRT3_get();
  public final static double SimTK_CBRT3 = opensimModelJNI.SimTK_CBRT3_get();
  public final static double SimTK_AVOGADROS_NUMBER = opensimModelJNI.SimTK_AVOGADROS_NUMBER_get();
  public final static double SimTK_MASS_OF_PROTON_IN_MD = opensimModelJNI.SimTK_MASS_OF_PROTON_IN_MD_get();
  public final static double SimTK_MASS_OF_NEUTRON_IN_MD = opensimModelJNI.SimTK_MASS_OF_NEUTRON_IN_MD_get();
  public final static double SimTK_MASS_OF_ELECTRON_IN_MD = opensimModelJNI.SimTK_MASS_OF_ELECTRON_IN_MD_get();
  public final static double SimTK_CHARGE_OF_PROTON_IN_SI = opensimModelJNI.SimTK_CHARGE_OF_PROTON_IN_SI_get();
  public final static double SimTK_CHARGE_OF_PROTON_IN_MD = opensimModelJNI.SimTK_CHARGE_OF_PROTON_IN_MD_get();
  public final static double SimTK_MOLAR_CHARGE_IN_SI = opensimModelJNI.SimTK_MOLAR_CHARGE_IN_SI_get();
  public final static double SimTK_MOLAR_CHARGE_IN_MD = opensimModelJNI.SimTK_MOLAR_CHARGE_IN_MD_get();
  public final static double SimTK_LIGHTSPEED_IN_SI = opensimModelJNI.SimTK_LIGHTSPEED_IN_SI_get();
  public final static double SimTK_LIGHTSPEED_IN_MD = opensimModelJNI.SimTK_LIGHTSPEED_IN_MD_get();
  public final static double SimTK_GRAVITATIONAL_CONSTANT_IN_SI = opensimModelJNI.SimTK_GRAVITATIONAL_CONSTANT_IN_SI_get();
  public final static double SimTK_GRAVITATIONAL_CONSTANT_IN_MD = opensimModelJNI.SimTK_GRAVITATIONAL_CONSTANT_IN_MD_get();
  public final static double SimTK_MAGNETIC_PERMEABILITY_IN_SI = opensimModelJNI.SimTK_MAGNETIC_PERMEABILITY_IN_SI_get();
  public final static double SimTK_MAGNETIC_PERMEABILITY_IN_MD = opensimModelJNI.SimTK_MAGNETIC_PERMEABILITY_IN_MD_get();
  public final static double SimTK_ELECTRIC_PERMITTIVITY_IN_SI = opensimModelJNI.SimTK_ELECTRIC_PERMITTIVITY_IN_SI_get();
  public final static double SimTK_ELECTRIC_PERMITTIVITY_IN_MD = opensimModelJNI.SimTK_ELECTRIC_PERMITTIVITY_IN_MD_get();
  public final static double SimTK_COULOMB_CONSTANT_IN_SI = opensimModelJNI.SimTK_COULOMB_CONSTANT_IN_SI_get();
  public final static double SimTK_COULOMB_CONSTANT_IN_MD = opensimModelJNI.SimTK_COULOMB_CONSTANT_IN_MD_get();
  public final static double SimTK_COULOMB_CONSTANT_IN_KCAL_ANGSTROM = opensimModelJNI.SimTK_COULOMB_CONSTANT_IN_KCAL_ANGSTROM_get();
  public final static double SimTK_MOLAR_GAS_CONSTANT_SI = opensimModelJNI.SimTK_MOLAR_GAS_CONSTANT_SI_get();
  public final static double SimTK_MOLAR_GAS_CONSTANT_MD = opensimModelJNI.SimTK_MOLAR_GAS_CONSTANT_MD_get();
  public final static double SimTK_MOLAR_GAS_CONSTANT_KCAL_ANGSTROM = opensimModelJNI.SimTK_MOLAR_GAS_CONSTANT_KCAL_ANGSTROM_get();
  public final static double SimTK_BOLTZMANN_CONSTANT_SI = opensimModelJNI.SimTK_BOLTZMANN_CONSTANT_SI_get();
  public final static double SimTK_BOLTZMANN_CONSTANT_MD = opensimModelJNI.SimTK_BOLTZMANN_CONSTANT_MD_get();
  public final static double SimTK_BOLTZMANN_CONSTANT_KCAL_ANGSTROM = opensimModelJNI.SimTK_BOLTZMANN_CONSTANT_KCAL_ANGSTROM_get();
  public final static double SimTK_RADIAN_TO_DEGREE = opensimModelJNI.SimTK_RADIAN_TO_DEGREE_get();
  public final static double SimTK_DEGREE_TO_RADIAN = opensimModelJNI.SimTK_DEGREE_TO_RADIAN_get();
  public final static double SimTK_NS_TO_S = opensimModelJNI.SimTK_NS_TO_S_get();
  public final static double SimTK_S_TO_NS = opensimModelJNI.SimTK_S_TO_NS_get();
  public final static double SimTK_KCAL_TO_KJOULE = opensimModelJNI.SimTK_KCAL_TO_KJOULE_get();
  public final static double SimTK_KJOULE_TO_KCAL = opensimModelJNI.SimTK_KJOULE_TO_KCAL_get();
  public final static double SimTK_DALTON_TO_GRAM = opensimModelJNI.SimTK_DALTON_TO_GRAM_get();
  public final static double SimTK_E_TO_COULOMB = opensimModelJNI.SimTK_E_TO_COULOMB_get();
  public final static double SimTK_EV_TO_JOULE = opensimModelJNI.SimTK_EV_TO_JOULE_get();
  public final static int SimTK_DEFAULT_PRECISION = opensimModelJNI.SimTK_DEFAULT_PRECISION_get();
}
