/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class OpenSenseUtilities {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public OpenSenseUtilities(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(OpenSenseUtilities obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimSimulationJNI.delete_OpenSenseUtilities(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static void rotateOrientationTable(TimeSeriesTableQuaternion quaternionsTable, Rotation rotationMatrix) {
    opensimSimulationJNI.OpenSenseUtilities_rotateOrientationTable(TimeSeriesTableQuaternion.getCPtr(quaternionsTable), quaternionsTable, Rotation.getCPtr(rotationMatrix), rotationMatrix);
  }

  public static TimeSeriesTableRotation convertQuaternionsToRotations(TimeSeriesTableQuaternion qauternionsTable) {
    return new TimeSeriesTableRotation(opensimSimulationJNI.OpenSenseUtilities_convertQuaternionsToRotations(TimeSeriesTableQuaternion.getCPtr(qauternionsTable), qauternionsTable), true);
  }

  public static Vec3 computeHeadingCorrection(Model model, TimeSeriesTableQuaternion quatTimeSeries, String baseIMU, CoordinateDirection arg3) {
    return new Vec3(opensimSimulationJNI.OpenSenseUtilities_computeHeadingCorrection(Model.getCPtr(model), model, TimeSeriesTableQuaternion.getCPtr(quatTimeSeries), quatTimeSeries, baseIMU, CoordinateDirection.getCPtr(arg3), arg3), true);
  }

  public static Model calibrateModelFromOrientations(IMUPlacer imuPalcer, boolean visualizeCalibratedModel) {
    return new Model(opensimSimulationJNI.OpenSenseUtilities_calibrateModelFromOrientations__SWIG_0(IMUPlacer.getCPtr(imuPalcer), imuPalcer, visualizeCalibratedModel), true);
  }

  public static Model calibrateModelFromOrientations(IMUPlacer imuPalcer) {
    return new Model(opensimSimulationJNI.OpenSenseUtilities_calibrateModelFromOrientations__SWIG_1(IMUPlacer.getCPtr(imuPalcer), imuPalcer), true);
  }

  public static SWIGTYPE_p_OpenSim__TimeSeriesTable_T_SimTK__Quaternion_T_SimTK__Real_t_t createOrientationsFileFromMarkers(String markersFile) {
    return new SWIGTYPE_p_OpenSim__TimeSeriesTable_T_SimTK__Quaternion_T_SimTK__Real_t_t(opensimSimulationJNI.OpenSenseUtilities_createOrientationsFileFromMarkers(markersFile), true);
  }

  public static Transform formTransformFromPoints(Vec3 op, Vec3 xp, Vec3 yp) {
    return new Transform(opensimSimulationJNI.OpenSenseUtilities_formTransformFromPoints(Vec3.getCPtr(op), op, Vec3.getCPtr(xp), xp, Vec3.getCPtr(yp), yp), true);
  }

  public OpenSenseUtilities() {
    this(opensimSimulationJNI.new_OpenSenseUtilities(), true);
  }

}
