/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class PointToPointSpring extends Force {
  private long swigCPtr;

  public PointToPointSpring(long cPtr, boolean cMemoryOwn) {
    super(opensimModelJNI.PointToPointSpring_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(PointToPointSpring obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimModelJNI.delete_PointToPointSpring(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static PointToPointSpring safeDownCast(OpenSimObject obj) {
    long cPtr = opensimModelJNI.PointToPointSpring_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new PointToPointSpring(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimModelJNI.PointToPointSpring_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimModelJNI.PointToPointSpring_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimModelJNI.PointToPointSpring_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new PointToPointSpring(cPtr, false);
  }

  public String getConcreteClassName() {
    return opensimModelJNI.PointToPointSpring_getConcreteClassName(swigCPtr, this);
  }

  public void setPropertyIndex_body1(SWIGTYPE_p_PropertyIndex value) {
    opensimModelJNI.PointToPointSpring_PropertyIndex_body1_set(swigCPtr, this, SWIGTYPE_p_PropertyIndex.getCPtr(value));
  }

  public SWIGTYPE_p_PropertyIndex getPropertyIndex_body1() {
    return new SWIGTYPE_p_PropertyIndex(opensimModelJNI.PointToPointSpring_PropertyIndex_body1_get(swigCPtr, this), true);
  }

  public void copyProperty_body1(PointToPointSpring source) {
    opensimModelJNI.PointToPointSpring_copyProperty_body1(swigCPtr, this, PointToPointSpring.getCPtr(source), source);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_std__string_t getProperty_body1() {
    return new SWIGTYPE_p_OpenSim__PropertyT_std__string_t(opensimModelJNI.PointToPointSpring_getProperty_body1(swigCPtr, this), false);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_std__string_t updProperty_body1() {
    return new SWIGTYPE_p_OpenSim__PropertyT_std__string_t(opensimModelJNI.PointToPointSpring_updProperty_body1(swigCPtr, this), false);
  }

  public String get_body1(int i) {
    return opensimModelJNI.PointToPointSpring_get_body1__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_std__string upd_body1(int i) {
    return new SWIGTYPE_p_std__string(opensimModelJNI.PointToPointSpring_upd_body1__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_body1(int i, String value) {
    opensimModelJNI.PointToPointSpring_set_body1__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_body1(String value) {
    return opensimModelJNI.PointToPointSpring_append_body1(swigCPtr, this, value);
  }

  public void constructProperty_body1() {
    opensimModelJNI.PointToPointSpring_constructProperty_body1__SWIG_0(swigCPtr, this);
  }

  public void constructProperty_body1(String initValue) {
    opensimModelJNI.PointToPointSpring_constructProperty_body1__SWIG_1(swigCPtr, this, initValue);
  }

  public String get_body1() {
    return opensimModelJNI.PointToPointSpring_get_body1__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_std__string upd_body1() {
    return new SWIGTYPE_p_std__string(opensimModelJNI.PointToPointSpring_upd_body1__SWIG_1(swigCPtr, this), false);
  }

  public void set_body1(String value) {
    opensimModelJNI.PointToPointSpring_set_body1__SWIG_1(swigCPtr, this, value);
  }

  public void setPropertyIndex_body2(SWIGTYPE_p_PropertyIndex value) {
    opensimModelJNI.PointToPointSpring_PropertyIndex_body2_set(swigCPtr, this, SWIGTYPE_p_PropertyIndex.getCPtr(value));
  }

  public SWIGTYPE_p_PropertyIndex getPropertyIndex_body2() {
    return new SWIGTYPE_p_PropertyIndex(opensimModelJNI.PointToPointSpring_PropertyIndex_body2_get(swigCPtr, this), true);
  }

  public void copyProperty_body2(PointToPointSpring source) {
    opensimModelJNI.PointToPointSpring_copyProperty_body2(swigCPtr, this, PointToPointSpring.getCPtr(source), source);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_std__string_t getProperty_body2() {
    return new SWIGTYPE_p_OpenSim__PropertyT_std__string_t(opensimModelJNI.PointToPointSpring_getProperty_body2(swigCPtr, this), false);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_std__string_t updProperty_body2() {
    return new SWIGTYPE_p_OpenSim__PropertyT_std__string_t(opensimModelJNI.PointToPointSpring_updProperty_body2(swigCPtr, this), false);
  }

  public String get_body2(int i) {
    return opensimModelJNI.PointToPointSpring_get_body2__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_std__string upd_body2(int i) {
    return new SWIGTYPE_p_std__string(opensimModelJNI.PointToPointSpring_upd_body2__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_body2(int i, String value) {
    opensimModelJNI.PointToPointSpring_set_body2__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_body2(String value) {
    return opensimModelJNI.PointToPointSpring_append_body2(swigCPtr, this, value);
  }

  public void constructProperty_body2() {
    opensimModelJNI.PointToPointSpring_constructProperty_body2__SWIG_0(swigCPtr, this);
  }

  public void constructProperty_body2(String initValue) {
    opensimModelJNI.PointToPointSpring_constructProperty_body2__SWIG_1(swigCPtr, this, initValue);
  }

  public String get_body2() {
    return opensimModelJNI.PointToPointSpring_get_body2__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_std__string upd_body2() {
    return new SWIGTYPE_p_std__string(opensimModelJNI.PointToPointSpring_upd_body2__SWIG_1(swigCPtr, this), false);
  }

  public void set_body2(String value) {
    opensimModelJNI.PointToPointSpring_set_body2__SWIG_1(swigCPtr, this, value);
  }

  public void setPropertyIndex_point1(SWIGTYPE_p_PropertyIndex value) {
    opensimModelJNI.PointToPointSpring_PropertyIndex_point1_set(swigCPtr, this, SWIGTYPE_p_PropertyIndex.getCPtr(value));
  }

  public SWIGTYPE_p_PropertyIndex getPropertyIndex_point1() {
    return new SWIGTYPE_p_PropertyIndex(opensimModelJNI.PointToPointSpring_PropertyIndex_point1_get(swigCPtr, this), true);
  }

  public void copyProperty_point1(PointToPointSpring source) {
    opensimModelJNI.PointToPointSpring_copyProperty_point1(swigCPtr, this, PointToPointSpring.getCPtr(source), source);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_SimTK__Vec3_t getProperty_point1() {
    return new SWIGTYPE_p_OpenSim__PropertyT_SimTK__Vec3_t(opensimModelJNI.PointToPointSpring_getProperty_point1(swigCPtr, this), false);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_SimTK__Vec3_t updProperty_point1() {
    return new SWIGTYPE_p_OpenSim__PropertyT_SimTK__Vec3_t(opensimModelJNI.PointToPointSpring_updProperty_point1(swigCPtr, this), false);
  }

  public SWIGTYPE_p_SimTK__Vec3 get_point1(int i) {
    return new SWIGTYPE_p_SimTK__Vec3(opensimModelJNI.PointToPointSpring_get_point1__SWIG_0(swigCPtr, this, i), false);
  }

  public SWIGTYPE_p_SimTK__Vec3 upd_point1(int i) {
    return new SWIGTYPE_p_SimTK__Vec3(opensimModelJNI.PointToPointSpring_upd_point1__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_point1(int i, SWIGTYPE_p_SimTK__Vec3 value) {
    opensimModelJNI.PointToPointSpring_set_point1__SWIG_0(swigCPtr, this, i, SWIGTYPE_p_SimTK__Vec3.getCPtr(value));
  }

  public int append_point1(SWIGTYPE_p_SimTK__Vec3 value) {
    return opensimModelJNI.PointToPointSpring_append_point1(swigCPtr, this, SWIGTYPE_p_SimTK__Vec3.getCPtr(value));
  }

  public void constructProperty_point1(SWIGTYPE_p_SimTK__Vec3 initValue) {
    opensimModelJNI.PointToPointSpring_constructProperty_point1(swigCPtr, this, SWIGTYPE_p_SimTK__Vec3.getCPtr(initValue));
  }

  public SWIGTYPE_p_SimTK__Vec3 get_point1() {
    return new SWIGTYPE_p_SimTK__Vec3(opensimModelJNI.PointToPointSpring_get_point1__SWIG_1(swigCPtr, this), false);
  }

  public SWIGTYPE_p_SimTK__Vec3 upd_point1() {
    return new SWIGTYPE_p_SimTK__Vec3(opensimModelJNI.PointToPointSpring_upd_point1__SWIG_1(swigCPtr, this), false);
  }

  public void set_point1(SWIGTYPE_p_SimTK__Vec3 value) {
    opensimModelJNI.PointToPointSpring_set_point1__SWIG_1(swigCPtr, this, SWIGTYPE_p_SimTK__Vec3.getCPtr(value));
  }

  public void setPropertyIndex_point2(SWIGTYPE_p_PropertyIndex value) {
    opensimModelJNI.PointToPointSpring_PropertyIndex_point2_set(swigCPtr, this, SWIGTYPE_p_PropertyIndex.getCPtr(value));
  }

  public SWIGTYPE_p_PropertyIndex getPropertyIndex_point2() {
    return new SWIGTYPE_p_PropertyIndex(opensimModelJNI.PointToPointSpring_PropertyIndex_point2_get(swigCPtr, this), true);
  }

  public void copyProperty_point2(PointToPointSpring source) {
    opensimModelJNI.PointToPointSpring_copyProperty_point2(swigCPtr, this, PointToPointSpring.getCPtr(source), source);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_SimTK__Vec3_t getProperty_point2() {
    return new SWIGTYPE_p_OpenSim__PropertyT_SimTK__Vec3_t(opensimModelJNI.PointToPointSpring_getProperty_point2(swigCPtr, this), false);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_SimTK__Vec3_t updProperty_point2() {
    return new SWIGTYPE_p_OpenSim__PropertyT_SimTK__Vec3_t(opensimModelJNI.PointToPointSpring_updProperty_point2(swigCPtr, this), false);
  }

  public SWIGTYPE_p_SimTK__Vec3 get_point2(int i) {
    return new SWIGTYPE_p_SimTK__Vec3(opensimModelJNI.PointToPointSpring_get_point2__SWIG_0(swigCPtr, this, i), false);
  }

  public SWIGTYPE_p_SimTK__Vec3 upd_point2(int i) {
    return new SWIGTYPE_p_SimTK__Vec3(opensimModelJNI.PointToPointSpring_upd_point2__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_point2(int i, SWIGTYPE_p_SimTK__Vec3 value) {
    opensimModelJNI.PointToPointSpring_set_point2__SWIG_0(swigCPtr, this, i, SWIGTYPE_p_SimTK__Vec3.getCPtr(value));
  }

  public int append_point2(SWIGTYPE_p_SimTK__Vec3 value) {
    return opensimModelJNI.PointToPointSpring_append_point2(swigCPtr, this, SWIGTYPE_p_SimTK__Vec3.getCPtr(value));
  }

  public void constructProperty_point2(SWIGTYPE_p_SimTK__Vec3 initValue) {
    opensimModelJNI.PointToPointSpring_constructProperty_point2(swigCPtr, this, SWIGTYPE_p_SimTK__Vec3.getCPtr(initValue));
  }

  public SWIGTYPE_p_SimTK__Vec3 get_point2() {
    return new SWIGTYPE_p_SimTK__Vec3(opensimModelJNI.PointToPointSpring_get_point2__SWIG_1(swigCPtr, this), false);
  }

  public SWIGTYPE_p_SimTK__Vec3 upd_point2() {
    return new SWIGTYPE_p_SimTK__Vec3(opensimModelJNI.PointToPointSpring_upd_point2__SWIG_1(swigCPtr, this), false);
  }

  public void set_point2(SWIGTYPE_p_SimTK__Vec3 value) {
    opensimModelJNI.PointToPointSpring_set_point2__SWIG_1(swigCPtr, this, SWIGTYPE_p_SimTK__Vec3.getCPtr(value));
  }

  public void setPropertyIndex_stiffness(SWIGTYPE_p_PropertyIndex value) {
    opensimModelJNI.PointToPointSpring_PropertyIndex_stiffness_set(swigCPtr, this, SWIGTYPE_p_PropertyIndex.getCPtr(value));
  }

  public SWIGTYPE_p_PropertyIndex getPropertyIndex_stiffness() {
    return new SWIGTYPE_p_PropertyIndex(opensimModelJNI.PointToPointSpring_PropertyIndex_stiffness_get(swigCPtr, this), true);
  }

  public void copyProperty_stiffness(PointToPointSpring source) {
    opensimModelJNI.PointToPointSpring_copyProperty_stiffness(swigCPtr, this, PointToPointSpring.getCPtr(source), source);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_double_t getProperty_stiffness() {
    return new SWIGTYPE_p_OpenSim__PropertyT_double_t(opensimModelJNI.PointToPointSpring_getProperty_stiffness(swigCPtr, this), false);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_double_t updProperty_stiffness() {
    return new SWIGTYPE_p_OpenSim__PropertyT_double_t(opensimModelJNI.PointToPointSpring_updProperty_stiffness(swigCPtr, this), false);
  }

  public double get_stiffness(int i) {
    return opensimModelJNI.PointToPointSpring_get_stiffness__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_stiffness(int i) {
    return new SWIGTYPE_p_double(opensimModelJNI.PointToPointSpring_upd_stiffness__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_stiffness(int i, double value) {
    opensimModelJNI.PointToPointSpring_set_stiffness__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_stiffness(double value) {
    return opensimModelJNI.PointToPointSpring_append_stiffness(swigCPtr, this, value);
  }

  public void constructProperty_stiffness(double initValue) {
    opensimModelJNI.PointToPointSpring_constructProperty_stiffness(swigCPtr, this, initValue);
  }

  public double get_stiffness() {
    return opensimModelJNI.PointToPointSpring_get_stiffness__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_stiffness() {
    return new SWIGTYPE_p_double(opensimModelJNI.PointToPointSpring_upd_stiffness__SWIG_1(swigCPtr, this), false);
  }

  public void set_stiffness(double value) {
    opensimModelJNI.PointToPointSpring_set_stiffness__SWIG_1(swigCPtr, this, value);
  }

  public void setPropertyIndex_rest_length(SWIGTYPE_p_PropertyIndex value) {
    opensimModelJNI.PointToPointSpring_PropertyIndex_rest_length_set(swigCPtr, this, SWIGTYPE_p_PropertyIndex.getCPtr(value));
  }

  public SWIGTYPE_p_PropertyIndex getPropertyIndex_rest_length() {
    return new SWIGTYPE_p_PropertyIndex(opensimModelJNI.PointToPointSpring_PropertyIndex_rest_length_get(swigCPtr, this), true);
  }

  public void copyProperty_rest_length(PointToPointSpring source) {
    opensimModelJNI.PointToPointSpring_copyProperty_rest_length(swigCPtr, this, PointToPointSpring.getCPtr(source), source);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_double_t getProperty_rest_length() {
    return new SWIGTYPE_p_OpenSim__PropertyT_double_t(opensimModelJNI.PointToPointSpring_getProperty_rest_length(swigCPtr, this), false);
  }

  public SWIGTYPE_p_OpenSim__PropertyT_double_t updProperty_rest_length() {
    return new SWIGTYPE_p_OpenSim__PropertyT_double_t(opensimModelJNI.PointToPointSpring_updProperty_rest_length(swigCPtr, this), false);
  }

  public double get_rest_length(int i) {
    return opensimModelJNI.PointToPointSpring_get_rest_length__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_rest_length(int i) {
    return new SWIGTYPE_p_double(opensimModelJNI.PointToPointSpring_upd_rest_length__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_rest_length(int i, double value) {
    opensimModelJNI.PointToPointSpring_set_rest_length__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_rest_length(double value) {
    return opensimModelJNI.PointToPointSpring_append_rest_length(swigCPtr, this, value);
  }

  public void constructProperty_rest_length(double initValue) {
    opensimModelJNI.PointToPointSpring_constructProperty_rest_length(swigCPtr, this, initValue);
  }

  public double get_rest_length() {
    return opensimModelJNI.PointToPointSpring_get_rest_length__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_rest_length() {
    return new SWIGTYPE_p_double(opensimModelJNI.PointToPointSpring_upd_rest_length__SWIG_1(swigCPtr, this), false);
  }

  public void set_rest_length(double value) {
    opensimModelJNI.PointToPointSpring_set_rest_length__SWIG_1(swigCPtr, this, value);
  }

  public PointToPointSpring() {
    this(opensimModelJNI.new_PointToPointSpring__SWIG_0(), true);
  }

  public PointToPointSpring(String body1Name, SWIGTYPE_p_SimTK__Vec3 point1, String body2Name, SWIGTYPE_p_SimTK__Vec3 point2, double stiffness, double restlength) {
    this(opensimModelJNI.new_PointToPointSpring__SWIG_1(body1Name, SWIGTYPE_p_SimTK__Vec3.getCPtr(point1), body2Name, SWIGTYPE_p_SimTK__Vec3.getCPtr(point2), stiffness, restlength), true);
  }

  public VisibleObject getDisplayer() {
    long cPtr = opensimModelJNI.PointToPointSpring_getDisplayer(swigCPtr, this);
    return (cPtr == 0) ? null : new VisibleObject(cPtr, false);
  }

  public void updateDisplayer(SWIGTYPE_p_SimTK__State s) {
    opensimModelJNI.PointToPointSpring_updateDisplayer(swigCPtr, this, SWIGTYPE_p_SimTK__State.getCPtr(s));
  }

  public void updateGeometry(SWIGTYPE_p_SimTK__State s) {
    opensimModelJNI.PointToPointSpring_updateGeometry(swigCPtr, this, SWIGTYPE_p_SimTK__State.getCPtr(s));
  }

  public void setBody1Name(String body1Name) {
    opensimModelJNI.PointToPointSpring_setBody1Name(swigCPtr, this, body1Name);
  }

  public void setBody2Name(String body2Name) {
    opensimModelJNI.PointToPointSpring_setBody2Name(swigCPtr, this, body2Name);
  }

  public String getBody1Name() {
    return opensimModelJNI.PointToPointSpring_getBody1Name(swigCPtr, this);
  }

  public String getBody2Name() {
    return opensimModelJNI.PointToPointSpring_getBody2Name(swigCPtr, this);
  }

  public void setPoint1(SWIGTYPE_p_SimTK__Vec3 aPosition) {
    opensimModelJNI.PointToPointSpring_setPoint1(swigCPtr, this, SWIGTYPE_p_SimTK__Vec3.getCPtr(aPosition));
  }

  public SWIGTYPE_p_SimTK__Vec3 getPoint1() {
    return new SWIGTYPE_p_SimTK__Vec3(opensimModelJNI.PointToPointSpring_getPoint1(swigCPtr, this), false);
  }

  public void setPoint2(SWIGTYPE_p_SimTK__Vec3 aPosition) {
    opensimModelJNI.PointToPointSpring_setPoint2(swigCPtr, this, SWIGTYPE_p_SimTK__Vec3.getCPtr(aPosition));
  }

  public SWIGTYPE_p_SimTK__Vec3 getPoint2() {
    return new SWIGTYPE_p_SimTK__Vec3(opensimModelJNI.PointToPointSpring_getPoint2(swigCPtr, this), false);
  }

  public void setStiffness(double stiffness) {
    opensimModelJNI.PointToPointSpring_setStiffness(swigCPtr, this, stiffness);
  }

  public double getStiffness() {
    return opensimModelJNI.PointToPointSpring_getStiffness(swigCPtr, this);
  }

  public void setRestlength(double restLength) {
    opensimModelJNI.PointToPointSpring_setRestlength(swigCPtr, this, restLength);
  }

  public double getRestlength() {
    return opensimModelJNI.PointToPointSpring_getRestlength(swigCPtr, this);
  }

  public void connectToModel(Model model) {
    opensimModelJNI.PointToPointSpring_connectToModel(swigCPtr, this, Model.getCPtr(model), model);
  }

  public void addToSystem(SWIGTYPE_p_SimTK__MultibodySystem system) {
    opensimModelJNI.PointToPointSpring_addToSystem(swigCPtr, this, SWIGTYPE_p_SimTK__MultibodySystem.getCPtr(system));
  }

  public ArrayStr getRecordLabels() {
    return new ArrayStr(opensimModelJNI.PointToPointSpring_getRecordLabels(swigCPtr, this), true);
  }

  public ArrayDouble getRecordValues(SWIGTYPE_p_SimTK__State state) {
    return new ArrayDouble(opensimModelJNI.PointToPointSpring_getRecordValues(swigCPtr, this, SWIGTYPE_p_SimTK__State.getCPtr(state)), true);
  }

}
