/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

/**
 *  This is a dataless rehash of the MatrixBase class to specialize it for RowVectors.<br>
 *  This mostly entails overriding a few of the methods. Note that all the MatrixBase<br>
 *  operations remain available if you static_cast&lt;&gt; this up to a MatrixBase.
 */
public class RowVectorBaseQuaternion extends MatrixBaseQuaternion {
  private transient long swigCPtr;

  public RowVectorBaseQuaternion(long cPtr, boolean cMemoryOwn) {
    super(opensimSimbodyJNI.RowVectorBaseQuaternion_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(RowVectorBaseQuaternion obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(RowVectorBaseQuaternion obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimSimbodyJNI.delete_RowVectorBaseQuaternion(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /**
   *  These constructors create new RowVectorBase objects which own their<br>
   *  own data and are (at least by default) resizable. The resulting matrices<br>
   *  are 1 x n with the number of rows locked at 1. If there is any data<br>
   *  allocated but not explicitly initialized, that data will be uninitialized<br>
   *  garbage in Release builds but will be initialized to NaN (at a performance<br>
   *  cost) in Debug builds.<br>
   *  <br>
   *  Default constructor makes a 1x0 matrix locked at 1 row; you can<br>
   *  provide an initial allocation if you want.
   */
  public RowVectorBaseQuaternion(int n) {
    this(opensimSimbodyJNI.new_RowVectorBaseQuaternion__SWIG_0(n), true);
  }

  /**
   *  These constructors create new RowVectorBase objects which own their<br>
   *  own data and are (at least by default) resizable. The resulting matrices<br>
   *  are 1 x n with the number of rows locked at 1. If there is any data<br>
   *  allocated but not explicitly initialized, that data will be uninitialized<br>
   *  garbage in Release builds but will be initialized to NaN (at a performance<br>
   *  cost) in Debug builds.<br>
   *  <br>
   *  Default constructor makes a 1x0 matrix locked at 1 row; you can<br>
   *  provide an initial allocation if you want.
   */
  public RowVectorBaseQuaternion() {
    this(opensimSimbodyJNI.new_RowVectorBaseQuaternion__SWIG_1(), true);
  }

  /**
   *  Copy constructor is a deep copy (not appropriate for views!). That<br>
   *  means it creates a new, densely packed vector whose elements are<br>
   *  initialized from the source object.    
   */
  public RowVectorBaseQuaternion(RowVectorBaseQuaternion source) {
    this(opensimSimbodyJNI.new_RowVectorBaseQuaternion__SWIG_2(RowVectorBaseQuaternion.getCPtr(source), source), true);
  }

  /**
   *  Construct an owner row vector of length n, with each element initialized to<br>
   *  the given value.
   */
  public RowVectorBaseQuaternion(int n, Quaternion initialValue) {
    this(opensimSimbodyJNI.new_RowVectorBaseQuaternion__SWIG_3(n, Quaternion.getCPtr(initialValue), initialValue), true);
  }

  public int size() {
    return opensimSimbodyJNI.RowVectorBaseQuaternion_size(swigCPtr, this);
  }

  public int nrow() {
    return opensimSimbodyJNI.RowVectorBaseQuaternion_nrow(swigCPtr, this);
  }

  public int ncol() {
    return opensimSimbodyJNI.RowVectorBaseQuaternion_ncol(swigCPtr, this);
  }

  public SWIGTYPE_p_ptrdiff_t nelt() {
    return new SWIGTYPE_p_ptrdiff_t(opensimSimbodyJNI.RowVectorBaseQuaternion_nelt(swigCPtr, this), true);
  }

  public RowVectorViewQuaternion index(SWIGTYPE_p_Array_T_int_t indices) {
    return new RowVectorViewQuaternion(opensimSimbodyJNI.RowVectorBaseQuaternion_index(swigCPtr, this, SWIGTYPE_p_Array_T_int_t.getCPtr(indices)), true);
  }

  public RowVectorViewQuaternion updIndex(SWIGTYPE_p_Array_T_int_t indices) {
    return new RowVectorViewQuaternion(opensimSimbodyJNI.RowVectorBaseQuaternion_updIndex(swigCPtr, this, SWIGTYPE_p_Array_T_int_t.getCPtr(indices)), true);
  }

  public RowVectorBaseQuaternion resize(int n) {
    return new RowVectorBaseQuaternion(opensimSimbodyJNI.RowVectorBaseQuaternion_resize(swigCPtr, this, n), false);
  }

  public RowVectorBaseQuaternion resizeKeep(int n) {
    return new RowVectorBaseQuaternion(opensimSimbodyJNI.RowVectorBaseQuaternion_resizeKeep(swigCPtr, this, n), false);
  }

  public void clear() {
    opensimSimbodyJNI.RowVectorBaseQuaternion_clear(swigCPtr, this);
  }

  public Quaternion sum() {
    return new Quaternion(opensimSimbodyJNI.RowVectorBaseQuaternion_sum(swigCPtr, this), true);
  }

  public SWIGTYPE_p_VectorIteratorT_SimTK__Quaternion_T_double_t_SimTK__RowVectorBaseT_SimTK__Quaternion_T_double_t_t_t begin() {
    return new SWIGTYPE_p_VectorIteratorT_SimTK__Quaternion_T_double_t_SimTK__RowVectorBaseT_SimTK__Quaternion_T_double_t_t_t(opensimSimbodyJNI.RowVectorBaseQuaternion_begin(swigCPtr, this), true);
  }

  public SWIGTYPE_p_VectorIteratorT_SimTK__Quaternion_T_double_t_SimTK__RowVectorBaseT_SimTK__Quaternion_T_double_t_t_t end() {
    return new SWIGTYPE_p_VectorIteratorT_SimTK__Quaternion_T_double_t_SimTK__RowVectorBaseT_SimTK__Quaternion_T_double_t_t_t(opensimSimbodyJNI.RowVectorBaseQuaternion_end(swigCPtr, this), true);
  }

}
