/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

/**
 * A class to represent Sphere geometry. 
 */
public class Sphere extends AnalyticGeometry {
  private transient long swigCPtr;

  public Sphere(long cPtr, boolean cMemoryOwn) {
    super(opensimSimulationJNI.Sphere_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Sphere obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimSimulationJNI.delete_Sphere(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static Sphere safeDownCast(OpenSimObject obj) {
    long cPtr = opensimSimulationJNI.Sphere_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new Sphere(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimSimulationJNI.Sphere_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimSimulationJNI.Sphere_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimSimulationJNI.Sphere_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new Sphere(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimSimulationJNI.Sphere_getConcreteClassName(swigCPtr, this);
  }

  public void copyProperty_radius(Sphere source) {
    opensimSimulationJNI.Sphere_copyProperty_radius(swigCPtr, this, Sphere.getCPtr(source), source);
  }

  public double get_radius(int i) {
    return opensimSimulationJNI.Sphere_get_radius__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_radius(int i) {
    return new SWIGTYPE_p_double(opensimSimulationJNI.Sphere_upd_radius__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_radius(int i, double value) {
    opensimSimulationJNI.Sphere_set_radius__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_radius(double value) {
    return opensimSimulationJNI.Sphere_append_radius(swigCPtr, this, value);
  }

  public void constructProperty_radius(double initValue) {
    opensimSimulationJNI.Sphere_constructProperty_radius(swigCPtr, this, initValue);
  }

  public double get_radius() {
    return opensimSimulationJNI.Sphere_get_radius__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_radius() {
    return new SWIGTYPE_p_double(opensimSimulationJNI.Sphere_upd_radius__SWIG_1(swigCPtr, this), false);
  }

  public void set_radius(double value) {
    opensimSimulationJNI.Sphere_set_radius__SWIG_1(swigCPtr, this, value);
  }

  /**
   *  Default constructor, creates a sphere of radius 1.0
   */
  public Sphere() {
    this(opensimSimulationJNI.new_Sphere__SWIG_0(), true);
  }

  /**
   *  Another constructor that takes in a specified radius
   */
  public Sphere(double radius) {
    this(opensimSimulationJNI.new_Sphere__SWIG_1(radius), true);
  }

}
