/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class StdVectorEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public StdVectorEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(StdVectorEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimModelCommonJNI.delete_StdVectorEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StdVectorEvent() {
    this(opensimModelCommonJNI.new_StdVectorEvent__SWIG_0(), true);
  }

  public StdVectorEvent(long n) {
    this(opensimModelCommonJNI.new_StdVectorEvent__SWIG_1(n), true);
  }

  public long size() {
    return opensimModelCommonJNI.StdVectorEvent_size(swigCPtr, this);
  }

  public long capacity() {
    return opensimModelCommonJNI.StdVectorEvent_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    opensimModelCommonJNI.StdVectorEvent_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return opensimModelCommonJNI.StdVectorEvent_isEmpty(swigCPtr, this);
  }

  public void clear() {
    opensimModelCommonJNI.StdVectorEvent_clear(swigCPtr, this);
  }

  public void add(Event x) {
    opensimModelCommonJNI.StdVectorEvent_add(swigCPtr, this, Event.getCPtr(x), x);
  }

  public Event get(int i) {
    return new Event(opensimModelCommonJNI.StdVectorEvent_get(swigCPtr, this, i), false);
  }

  public void set(int i, Event val) {
    opensimModelCommonJNI.StdVectorEvent_set(swigCPtr, this, i, Event.getCPtr(val), val);
  }

}
