name: opensim-application-core-PR

on:
  workflow_dispatch:
    inputs:
      distinct_id:
        required: true

jobs:
  windows:
    name: Windows

    runs-on: windows-2022

    steps:
      - name: Log distinct ID
        run: echo ${{ inputs.distinct_id }}

      - name: Checkout opensim-gui
        uses: actions/checkout@v4

      - name: Build opensim-core
        uses: ./actions/build-opensim-core
        with:
          repository: opensim-org/opensim-core

      - name: Build GUI installer
        uses: ./actions/build-gui-installer
